project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 1a"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "Hands-on Exercise 1b"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "Hands-on Exercise 2a"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "Hands-on Exercise 2b"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "Take-home Exercise"
        menu:
        - text: "Take-home Exercise 1a"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

