<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Linh Nguyen">
<meta name="dcterms.date" content="2025-10-17">
<title>Hands-on Exercise 7 | Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method – ISSS626-GAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-941d7e14017e1a43777b60853515243b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../../styles.css">
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">
<li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html">
 <span class="dropdown-text">Hands-on Exercise 1a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html">
 <span class="dropdown-text">Hands-on Exercise 1b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html">
 <span class="dropdown-text">Hands-on Exercise 2a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html">
 <span class="dropdown-text">Hands-on Exercise 2b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html">
 <span class="dropdown-text">Hands-on Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html">
 <span class="dropdown-text">Hands-on Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">
<li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03a.html">
 <span class="dropdown-text">In-class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03b.html">
 <span class="dropdown-text">In-class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">
<li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
</li>
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a>
  <ul class="collapse">
<li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">1.1</span> The Data</a></li>
  <li><a href="#import-r-packages" id="toc-import-r-packages" class="nav-link" data-scroll-target="#import-r-packages"><span class="header-section-number">1.2</span> Import R Packages</a></li>
  <li><a href="#about-gwmodel" id="toc-about-gwmodel" class="nav-link" data-scroll-target="#about-gwmodel"><span class="header-section-number">1.3</span> About GWmodel</a></li>
  </ul>
</li>
  <li>
<a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">2</span> Data Wrangling</a>
  <ul class="collapse">
<li><a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling"><span class="header-section-number">2.1</span> Geospatial data wrangling</a></li>
  <li><a href="#aspatial-data-wrangling" id="toc-aspatial-data-wrangling" class="nav-link" data-scroll-target="#aspatial-data-wrangling"><span class="header-section-number">2.2</span> Aspatial data wrangling</a></li>
  </ul>
</li>
  <li>
<a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">3</span> Exploratory data analysis (EDA)</a>
  <ul class="collapse">
<li><a href="#eda-using-statistical-graphics" id="toc-eda-using-statistical-graphics" class="nav-link" data-scroll-target="#eda-using-statistical-graphics"><span class="header-section-number">3.1</span> EDA using statistical graphics</a></li>
  <li><a href="#multiple-histogram-plots-distributions-of-variables" id="toc-multiple-histogram-plots-distributions-of-variables" class="nav-link" data-scroll-target="#multiple-histogram-plots-distributions-of-variables"><span class="header-section-number">3.2</span> Multiple histogram plots distributions of variables</a></li>
  <li><a href="#draw-statistical-point-map" id="toc-draw-statistical-point-map" class="nav-link" data-scroll-target="#draw-statistical-point-map"><span class="header-section-number">3.3</span> Draw statistical point map</a></li>
  </ul>
</li>
  <li>
<a href="#hedonic-pricing-modelling-in-r" id="toc-hedonic-pricing-modelling-in-r" class="nav-link" data-scroll-target="#hedonic-pricing-modelling-in-r"><span class="header-section-number">4</span> Hedonic pricing modelling in R</a>
  <ul class="collapse">
<li><a href="#simple-linear-regression-method" id="toc-simple-linear-regression-method" class="nav-link" data-scroll-target="#simple-linear-regression-method"><span class="header-section-number">4.1</span> Simple linear regression method</a></li>
  <li><a href="#multiple-linear-regression-method" id="toc-multiple-linear-regression-method" class="nav-link" data-scroll-target="#multiple-linear-regression-method"><span class="header-section-number">4.2</span> Multiple linear regression method</a></li>
  <li><a href="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method" id="toc-building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="nav-link" data-scroll-target="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method"><span class="header-section-number">4.3</span> Building a hedonic pricing model using multiple linear regression method</a></li>
  <li><a href="#revising-the-model" id="toc-revising-the-model" class="nav-link" data-scroll-target="#revising-the-model"><span class="header-section-number">4.4</span> Revising the model</a></li>
  <li><a href="#preparing-publication-quality-table-gtsummary-method" id="toc-preparing-publication-quality-table-gtsummary-method" class="nav-link" data-scroll-target="#preparing-publication-quality-table-gtsummary-method"><span class="header-section-number">4.5</span> Preparing Publication Quality Table: gtsummary method</a></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics"><span class="header-section-number">4.6</span> Regression Diagnostics</a></li>
  </ul>
</li>
  <li>
<a href="#building-hedonic-pricing-models-using-gwmodel" id="toc-building-hedonic-pricing-models-using-gwmodel" class="nav-link" data-scroll-target="#building-hedonic-pricing-models-using-gwmodel"><span class="header-section-number">5</span> Building Hedonic Pricing Models using GWmodel</a>
  <ul class="collapse">
<li><a href="#building-fixed-bandwidth-gwr-model" id="toc-building-fixed-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-fixed-bandwidth-gwr-model"><span class="header-section-number">5.1</span> Building Fixed Bandwidth GWR Model</a></li>
  <li><a href="#building-adaptive-bandwidth-gwr-model" id="toc-building-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-adaptive-bandwidth-gwr-model"><span class="header-section-number">5.2</span> Building Adaptive Bandwidth GWR Model</a></li>
  <li><a href="#visualising-gwr-output" id="toc-visualising-gwr-output" class="nav-link" data-scroll-target="#visualising-gwr-output"><span class="header-section-number">5.3</span> Visualising GWR Output</a></li>
  <li><a href="#visualising-local-r2" id="toc-visualising-local-r2" class="nav-link" data-scroll-target="#visualising-local-r2"><span class="header-section-number">5.4</span> Visualising local R2</a></li>
  <li><a href="#visualising-coefficient-estimates" id="toc-visualising-coefficient-estimates" class="nav-link" data-scroll-target="#visualising-coefficient-estimates"><span class="header-section-number">5.5</span> Visualising coefficient estimates</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Hands-on Exercise 7 | Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</h1>
<p class="subtitle lead">In this hands-on exercise, we will learn how to build hedonic pricing models by using GWR methods. The dependent variable is the resale prices of condominium in 2015. The independent variables are divided into either structural and locational.</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Linh Nguyen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 17, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 18, 2025</p>
    </div>
  </div>
    
  </div>
  


</header><section id="overview" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="overview">
<span class="header-section-number">1</span> Overview</h2>
<p>Geographically weighted regression (GWR) accounts for non-stationary variables (e.g., climate, demographics, environment) and models local relationships between independent variables and a dependent variable. In this exercise, we’ll build hedonic pricing models using GWR, with the 2015 resale prices of condominiums as the dependent variable and structural and locational factors as independent variables.</p>
<section id="the-data" class="level3" data-number="1.1"><h3 data-number="1.1" class="anchored" data-anchor-id="the-data">
<span class="header-section-number">1.1</span> The Data</h3>
<table class="caption-top table">
<thead><tr class="header">
<th>Dataset</th>
<th>Source</th>
<th>Description</th>
<th>Format</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Master Plan 2014 Subzone Boundary (Web)</strong></td>
<td><a href="https://data.gov.sg/">data.gov.sg</a></td>
<td>Geospatial boundaries for Singapore’s planning subzones.</td>
<td>ESRI Shapefile</td>
</tr>
<tr class="even">
<td>Condo resale 2015</td>
<td></td>
<td></td>
<td>CSV</td>
</tr>
</tbody>
</table></section><section id="import-r-packages" class="level3" data-number="1.2"><h3 data-number="1.2" class="anchored" data-anchor-id="import-r-packages">
<span class="header-section-number">1.2</span> Import R Packages</h3>
<p>We will be using the following R packages:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>R Package</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><a href="https://olsrr.rsquaredacademy.com/"><strong>olsrr</strong></a></td>
<td>R package for building OLS and performing diagnostics tests</td>
</tr>
<tr class="even">
<td><a href="https://cran.r-project.org/web/packages/GWmodel/index.html"><strong>GWmodel</strong></a></td>
<td>R package for calibrating geographical weighted family of models</td>
</tr>
<tr class="odd">
<td><a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html"><strong>corrplot</strong></a></td>
<td>R package for multivariate data visualisation and analysis</td>
</tr>
<tr class="even">
<td><strong>sf</strong></td>
<td>Spatial data handling</td>
</tr>
<tr class="odd">
<td><strong>tidyverse</strong></td>
<td>Attribute data handling with <strong>readr</strong>, <strong>ggplot2</strong> and <strong>dplyr</strong>
</td>
</tr>
<tr class="even">
<td><strong>tmap</strong></td>
<td>Do Choropleth mapping</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">olsrr</span>, <span class="va">corrplot</span>, <span class="va">ggpubr</span>, <span class="va">sf</span>, <span class="va">sfdep</span>, <span class="va">GWmodel</span>, <span class="va">tmap</span>, <span class="va">tidyverse</span>, <span class="va">gtsummary</span>,</span>
<span>               <span class="va">performance</span>, <span class="va">RColorBrewer</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="about-gwmodel" class="level3" data-number="1.3"><h3 data-number="1.3" class="anchored" data-anchor-id="about-gwmodel">
<span class="header-section-number">1.3</span> About GWmodel</h3>
<p><a href="https://www.jstatsoft.org/article/view/v063i17"><strong>GWmodel</strong></a> package provides a collection of localised spatial statistical methods, namely: GW summary statistics, GW principal components analysis, GW discriminant analysis and various forms of GW regression; some of which are provided in basic and robust (outlier resistant) forms. Commonly, outputs or parameters of the GWmodel are mapped to provide a useful exploratory tool, which can often precede (and direct) a more traditional or sophisticated statistical analysis.</p>
</section></section><section id="data-wrangling" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="data-wrangling">
<span class="header-section-number">2</span> Data Wrangling</h2>
<section id="geospatial-data-wrangling" class="level3" data-number="2.1"><h3 data-number="2.1" class="anchored" data-anchor-id="geospatial-data-wrangling">
<span class="header-section-number">2.1</span> Geospatial data wrangling</h3>
<section id="import-geospatial-data" class="level4" data-number="2.1.1"><h4 data-number="2.1.1" class="anchored" data-anchor-id="import-geospatial-data">
<span class="header-section-number">2.1.1</span> Import geospatial data</h4>
<p>The geospatial data used in this hands-on exercise is called MP14_SUBZONE_WEB_PL. It is in ESRI shapefile format. The shapefile consists of URA Master Plan 2014’s planning subzone boundaries. Polygon features are used to represent these geographic boundaries. The GIS data is in svy21 projected coordinates systems.</p>
<p>The code chunk below is used to import <em>MP_SUBZONE_WEB_PL</em> shapefile by using <code>st_read()</code> of <strong>sf</strong> packages.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mpsz</span> <span class="op">=</span> <span class="fu">st_read</span><span class="op">(</span>dsn <span class="op">=</span> <span class="st">"data/geospatial"</span>, layer <span class="op">=</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `D:\ngoclinhnguyen-2806\ISSS626-GAA\Hands-on_Ex\Hands-on_Ex07\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
</section><section id="update-crs-information" class="level4" data-number="2.1.2"><h4 data-number="2.1.2" class="anchored" data-anchor-id="update-crs-information">
<span class="header-section-number">2.1.2</span> Update CRS information</h4>
<p>The code chunk below updates the newly imported <em>mpsz</em> with the <strong>correct ESPG code (i.e.&nbsp;3414)</strong></p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mpsz_svy21</span> <span class="op">&lt;-</span> <span class="fu">st_transform</span><span class="op">(</span><span class="va">mpsz</span>, <span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s verify the newly transformed <em>mpsz_svy21</em>.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_crs</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<p>Notice that the EPSG: <strong>is indicated as <em>3414</em> now.</strong></p>
<p>Next, we will reveal the extent of <em>mpsz_svy21</em> by using <code>st_bbox()</code> of sf package. The print below reports the extent of mpsz_svy21 layer by its l<strong>ower and upper limits</strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_bbox</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     xmin      ymin      xmax      ymax 
 2667.538 15748.721 56396.440 50256.334 </code></pre>
</div>
</div>
</section></section><section id="aspatial-data-wrangling" class="level3" data-number="2.2"><h3 data-number="2.2" class="anchored" data-anchor-id="aspatial-data-wrangling">
<span class="header-section-number">2.2</span> Aspatial data wrangling</h3>
<section id="import-aspatial-data" class="level4" data-number="2.2.1"><h4 data-number="2.2.1" class="anchored" data-anchor-id="import-aspatial-data">
<span class="header-section-number">2.2.1</span> Import Aspatial data</h4>
<p>The <em>condo_resale_2015</em> is in csv file format. The codes chunk below uses <code>read_csv()</code> function of <strong>readr</strong> package to import <em>condo_resale_2015</em> into R as a tibble data frame called <em>condo_resale</em>.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale</span> <span class="op">=</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/aspatial/Condo_resale_2015.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glimpse</span><span class="op">(</span><span class="va">condo_resale</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 23
$ LATITUDE             &lt;dbl&gt; 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…
$ LONGITUDE            &lt;dbl&gt; 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…
$ POSTCODE             &lt;dbl&gt; 118635, 288420, 267833, 258380, 467169, 466472, 3…
$ SELLING_PRICE        &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1320…
$ AREA_SQM             &lt;dbl&gt; 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…
$ AGE                  &lt;dbl&gt; 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…
$ PROX_CBD             &lt;dbl&gt; 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…
$ PROX_CHILDCARE       &lt;dbl&gt; 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…
$ PROX_ELDERLYCARE     &lt;dbl&gt; 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…
$ PROX_URA_GROWTH_AREA &lt;dbl&gt; 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…
$ PROX_HAWKER_MARKET   &lt;dbl&gt; 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…
$ PROX_KINDERGARTEN    &lt;dbl&gt; 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…
$ PROX_MRT             &lt;dbl&gt; 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…
$ PROX_PARK            &lt;dbl&gt; 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…
$ PROX_PRIMARY_SCH     &lt;dbl&gt; 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…
$ PROX_TOP_PRIMARY_SCH &lt;dbl&gt; 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…
$ PROX_SHOPPING_MALL   &lt;dbl&gt; 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…
$ PROX_SUPERMARKET     &lt;dbl&gt; 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…
$ PROX_BUS_STOP        &lt;dbl&gt; 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…
$ NO_Of_UNITS          &lt;dbl&gt; 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…
$ FAMILY_FRIENDLY      &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…
$ FREEHOLD             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
$ LEASEHOLD_99YR       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
</div>
<p><strong>Look at the data set’s longitude and latitude.</strong></p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">$</span><span class="va">LONGITUDE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 103.7802 103.8123 103.7971 103.8247 103.9505 103.9386</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">$</span><span class="va">LATITUDE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.287145 1.328698 1.313727 1.308563 1.321437 1.314198</code></pre>
</div>
</div>
<p>The print above reveals that the values of <em>LONGITITUDE</em> and <em>LATITUDE</em> fields are in decimal degree. Most probably wgs84 geographic coordinate system is used.</p>
<p>Next, <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> of base R is used to display the summary statistics of <em>cond_resale</em> tibble data frame.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     
 Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  
 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  
 Median :1.328   Median :103.8   Median :469298   Median : 1383222  
 Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  
 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  
 Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  
    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    
 Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  
 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  
 Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  
 Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  
 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  
 Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  
 PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN 
 Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  
 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  
 Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  
 Mean   :1.05352   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  
 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  
 Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  
    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH
 Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     
 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     
 Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     
 Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     
 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     
 Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     
 PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    
 Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  
 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  
 Median :0.9357     Median :0.5687   Median :0.151711   Median : 360.0  
 Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  
 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  
 Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  
 FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :0.0000  
 Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  </code></pre>
</div>
</div>
</section><section id="convert-aspatial-data-frame-into-a-sf-object" class="level4" data-number="2.2.2"><h4 data-number="2.2.2" class="anchored" data-anchor-id="convert-aspatial-data-frame-into-a-sf-object">
<span class="header-section-number">2.2.2</span> Convert aspatial data frame into a sf object</h4>
<p>Currently, the <em>condo_resale</em> tibble data frame is aspatial. We will convert it to a <strong>sf</strong> object. The code chunk below converts condo_resale data frame into a simple feature data frame by using <code>st_as_sf()</code> of <strong>sf</strong> packages.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="fu">st_as_sf</span><span class="op">(</span><span class="va">condo_resale</span>,</span>
<span>                            coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"LONGITUDE"</span>, <span class="st">"LATITUDE"</span><span class="op">)</span>,</span>
<span>                            crs<span class="op">=</span><span class="fl">4326</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">st_transform</span><span class="op">(</span>crs<span class="op">=</span><span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Note</strong> Notice that <code>st_transform()</code> of <strong>sf</strong> package is used to convert the coordinates from wgs84 (i.e.&nbsp;crs:4326) to svy21 (i.e.&nbsp;crs=3414).</p>
<p>Let’s list the content of <em>condo_resale.sf</em> object. Notice that the output is in point feature data frame.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale.sf</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 21 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2
Projected CRS: SVY21 / Singapore TM
# A tibble: 6 × 22
  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE
     &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
1   118635       3000000      309    30     7.94          0.166            2.52 
2   288420       3880000      290    32     6.61          0.280            1.93 
3   267833       3325000      248    33     6.90          0.429            0.502
4   258380       4250000      127     7     4.04          0.395            1.99 
5   467169       1400000      145    28    11.8           0.119            1.12 
6   466472       1320000      139    22    10.3           0.125            0.789
# ℹ 15 more variables: PROX_URA_GROWTH_AREA &lt;dbl&gt;, PROX_HAWKER_MARKET &lt;dbl&gt;,
#   PROX_KINDERGARTEN &lt;dbl&gt;, PROX_MRT &lt;dbl&gt;, PROX_PARK &lt;dbl&gt;,
#   PROX_PRIMARY_SCH &lt;dbl&gt;, PROX_TOP_PRIMARY_SCH &lt;dbl&gt;,
#   PROX_SHOPPING_MALL &lt;dbl&gt;, PROX_SUPERMARKET &lt;dbl&gt;, PROX_BUS_STOP &lt;dbl&gt;,
#   NO_Of_UNITS &lt;dbl&gt;, FAMILY_FRIENDLY &lt;dbl&gt;, FREEHOLD &lt;dbl&gt;,
#   LEASEHOLD_99YR &lt;dbl&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
</section></section></section><section id="exploratory-data-analysis-eda" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="exploratory-data-analysis-eda">
<span class="header-section-number">3</span> Exploratory data analysis (EDA)</h2>
<p>In the section, we will use statistical graphics functions of <strong>ggplot2</strong> package to perform EDA.</p>
<section id="eda-using-statistical-graphics" class="level3" data-number="3.1"><h3 data-number="3.1" class="anchored" data-anchor-id="eda-using-statistical-graphics">
<span class="header-section-number">3.1</span> EDA using statistical graphics</h3>
<p>We can plot the distribution of <em>SELLING_PRICE</em> by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#CBCBCB"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>plot.background <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram shows a right skewed distribution. This means that more condominium units were transacted at relatively lower prices.</p>
<p>Statistically, the skewed dsitribution can be normalised by using log transformation. The code chunk below is used to derive a new variable called <em>LOG_SELLING_PRICE</em> by using a log transformation on the variable <em>SELLING_PRICE</em>. It is performed using <code>mutate()</code> of <strong>dplyr</strong> package.</p>
<p><strong>Below histogram using logarithmic graph looks less skewed after the transformation.</strong></p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="va">condo_resale.sf</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>`LOG_SELLING_PRICE` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">SELLING_PRICE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`LOG_SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#CBCBCB"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>plot.background <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="multiple-histogram-plots-distributions-of-variables" class="level3" data-number="3.2"><h3 data-number="3.2" class="anchored" data-anchor-id="multiple-histogram-plots-distributions-of-variables">
<span class="header-section-number">3.2</span> Multiple histogram plots distributions of variables</h3>
<p>In this section, we will draw a small multiple histograms (also known as trellis plot) by using <code>ggarrange()</code> of <a href="https://cran.r-project.org/web/packages/ggpubr/index.html"><strong>ggpubr</strong></a> package.</p>
<p>Below we create 12 histograms. Then, <code>ggarrange()</code> is used to organised these histogram into a 3 columns by 4 rows small multiple plot.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">custom_theme</span> <span class="op">&lt;-</span> <span class="fu">theme</span><span class="op">(</span></span>
<span>  axis.text.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">7</span><span class="op">)</span>,</span>
<span>  axis.title.x <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">9</span><span class="op">)</span>,</span>
<span>  plot.background <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">AREA_SQM</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`AREA_SQM`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">AGE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>              <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`AGE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_CBD</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_CBD`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_CHILDCARE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                         <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_CHILDCARE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_ELDERLYCARE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                           <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_ELDERLYCARE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                               <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_URA_GROWTH_AREA`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_HAWKER_MARKET</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                             <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_HAWKER_MARKET`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_KINDERGARTEN</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                            <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_KINDERGARTEN`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_MRT</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_MRT`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_PARK</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                    <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_PARK`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_PRIMARY_SCH</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                           <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_PRIMARY_SCH`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="va">PROX_TOP_PRIMARY_SCH</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                               <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_TOP_PRIMARY_SCH`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"#777C6D"</span>, fill<span class="op">=</span><span class="st">"#B7B89F"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">custom_theme</span></span>
<span></span>
<span><span class="fu">ggarrange</span><span class="op">(</span><span class="va">AREA_SQM</span>, <span class="va">AGE</span>, <span class="va">PROX_CBD</span>, <span class="va">PROX_CHILDCARE</span>, </span>
<span>          <span class="va">PROX_ELDERLYCARE</span>, <span class="va">PROX_URA_GROWTH_AREA</span>,</span>
<span>          <span class="va">PROX_HAWKER_MARKET</span>, <span class="va">PROX_KINDERGARTEN</span>, <span class="va">PROX_MRT</span>,</span>
<span>          <span class="va">PROX_PARK</span>, <span class="va">PROX_PRIMARY_SCH</span>, <span class="va">PROX_TOP_PRIMARY_SCH</span>,  </span>
<span>          ncol <span class="op">=</span> <span class="fl">3</span>, nrow <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section><section id="draw-statistical-point-map" class="level3" data-number="3.3"><h3 data-number="3.3" class="anchored" data-anchor-id="draw-statistical-point-map">
<span class="header-section-number">3.3</span> Draw statistical point map</h3>
<p>Finally, we want to reveal the geospatial distribution condominium resale prices in Singapore. The map will be prepared by using <strong>tmap</strong> package.</p>
<p>First, we will turn on the interactive mode of tmap.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we will create a interactive point symbol map.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_text</span><span class="op">(</span><span class="st">"SUBZONE_N"</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">condo_resale.sf</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"SELLING_PRICE"</span>,</span>
<span>          fill_alpha <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>          size <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>          fill.scale <span class="op">=</span> <span class="fu">tm_scale_intervals</span><span class="op">(</span></span>
<span>            style<span class="op">=</span><span class="st">"quantile"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_view</span><span class="op">(</span>set_zoom_limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">16</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Note</strong></p>
<ul>
<li><p><a href="https://www.rdocumentation.org/packages/tmap/versions/2.2/topics/tm_symbols"><code>tm_dots()</code></a> is used instead of <code>tm_bubbles(), so it's not oversized.</code></p></li>
<li><p><code>set_zoom_limits</code> argument of <code>tm_view()</code> sets the minimum and maximum zoom level to 11 and 14 respectively.</p></li>
</ul>
<p><strong>Don’t forget to return to the <em>“plot”</em> mode.</strong></p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="hedonic-pricing-modelling-in-r" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="hedonic-pricing-modelling-in-r">
<span class="header-section-number">4</span> Hedonic pricing modelling in R</h2>
<p>In this section, we will build hedonic pricing models for condominium resale units using <a href="https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/lm"><code>lm()</code></a> of R base.</p>
<section id="simple-linear-regression-method" class="level3" data-number="4.1"><h3 data-number="4.1" class="anchored" data-anchor-id="simple-linear-regression-method">
<span class="header-section-number">4.1</span> Simple linear regression method</h3>
<p>First, we will build a simple linear regression model by using <em>SELLING_PRICE</em> as the dependent variable and <em>AREA_SQM</em> as the independent variable. <strong>[<em>AREA_SQM</em>➡️ <em>SELLING_PRICE</em> ]</strong></p>
<p><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> returns an object of class “lm” or for multiple responses of class c(“mlm”, “lm”).</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.slr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula<span class="op">=</span><span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span>, </span>
<span>                data <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The functions <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> can be used to obtain and print a summary and analysis of variance table of the results. The generic accessor functions coefficients, effects, fitted.values and residuals extract various useful features of the value returned by <code>lm</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.slr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3695815  -391764   -87517   258900 13503875 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***
AREA_SQM      14719.0      428.1  34.381  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 942700 on 1434 degrees of freedom
Multiple R-squared:  0.4518,    Adjusted R-squared:  0.4515 
F-statistic:  1182 on 1 and 1434 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="markgoals-container">
<p>The output report reveals that the SELLING_PRICE can be explained by using the formula:</p>
<pre><code>      *y = -258121.1 + 14719x1*</code></pre>
<ul>
<li><p>The R-squared of 0.4518 reveals that the simple regression model built is able to explain about 45% of the resale prices.</p></li>
<li><p>Since p-value is much smaller than 0.0001, we will <strong>reject the null hypothesis</strong> that mean is a good estimator of <em>SELLING_PRICE</em>. This will allow us to infer that <strong>simple linear regression model above is a good estimator of <em>SELLING_PRICE</em>.</strong></p></li>
<li><p>The <strong>Coefficients:</strong> section of the report reveals that the p-values of both the estimates of the Intercept and ARA_SQM are smaller than 0.001. In view of this, the null hypothesis of the B0 and B1 are equal to 0 will be rejected. As a results, we will be able to infer that the B0 and B1 are good parameter estimates.</p></li>
</ul>
</div>
<p>To visualise the best fit curve on a scatterplot, we can incorporate <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> as a method function in ggplot’s geometry as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>,  </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`AREA_SQM`</span>, y<span class="op">=</span><span class="va">`SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">0.3</span>, color <span class="op">=</span> <span class="st">"#777C6D"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>plot.background <span class="op">=</span> <span class="fu">element_rect</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The figure above reveals that there are a few statistical outliers with relatively high selling prices.</p>
</section><section id="multiple-linear-regression-method" class="level3" data-number="4.2"><h3 data-number="4.2" class="anchored" data-anchor-id="multiple-linear-regression-method">
<span class="header-section-number">4.2</span> Multiple linear regression method</h3>
<section id="visualising-the-relationships-of-the-independent-variables" class="level4" data-number="4.2.1"><h4 data-number="4.2.1" class="anchored" data-anchor-id="visualising-the-relationships-of-the-independent-variables">
<span class="header-section-number">4.2.1</span> Visualising the relationships of the independent variables</h4>
<p>Before building a multiple regression model, it is important to ensure that the indepdent variables used are not highly correlated to each other. If these highly correlated independent variables are used in building a regression model by mistake, the quality of the model will be compromised. This phenomenon is known as <strong>multicollinearity</strong> in statistics.</p>
<p>Correlation matrix is commonly used to visualise the relationships between the independent variables. Beside the <code><a href="https://rdrr.io/r/graphics/pairs.html">pairs()</a></code> of R, there are many packages support the display of a correlation matrix. In this section, the <a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html"><strong>corrplot</strong></a> package will be used.</p>
<p>Below we will plot a scatterplot matrix of the relationship between the independent variables in <em>condo_resale</em> data.frame.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>bg <span class="op">=</span> <span class="st">"grey"</span><span class="op">)</span> </span>
<span><span class="fu">corrplot</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">[</span>, <span class="fl">5</span><span class="op">:</span><span class="fl">23</span><span class="op">]</span><span class="op">)</span>, </span>
<span>         bg <span class="op">=</span> <span class="st">"#E7F0DC"</span>,</span>
<span>         diag <span class="op">=</span> <span class="cn">FALSE</span>, </span>
<span>         order <span class="op">=</span> <span class="st">"AOE"</span>,</span>
<span>         tl.pos <span class="op">=</span> <span class="st">"td"</span>, </span>
<span>         tl.cex <span class="op">=</span> <span class="fl">0.7</span>, </span>
<span>         tl.col <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>         tl.srt <span class="op">=</span> <span class="fl">45</span>,</span>
<span>         method <span class="op">=</span> <span class="st">"number"</span>, </span>
<span>         number.cex <span class="op">=</span> <span class="fl">0.9</span>,</span>
<span>         type <span class="op">=</span> <span class="st">"upper"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p><strong>Learning</strong></p>
<ul>
<li><p>Matrix reorder is very important for mining the hiden structure and patter in the matrix. There are four methods in corrplot (parameter order), named “AOE”, “FPC”, “hclust”, “alphabet”. In the code chunk above, <strong>AOE order</strong> is used. It orders the variables by using the <em>angular order of the eigenvectors</em> method suggested by <a href="https://www.datavis.ca/papers/corrgram.pdf">Michael Friendly</a>.</p></li>
<li><p>From the scatterplot matrix, it is clear that <strong><em>Freehold</em></strong> is highly correlated to <strong><em>LEASE_99YEAR</em></strong>. In view of this, it is wiser to only include either one of them in the subsequent model building. As a result, <strong><em>LEASE_99YEAR</em></strong> is excluded in the subsequent model building.</p></li>
</ul></section></section><section id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="level3" data-number="4.3"><h3 data-number="4.3" class="anchored" data-anchor-id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method">
<span class="header-section-number">4.3</span> Building a hedonic pricing model using multiple linear regression method</h3>
<p>The code chunk below using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> to calibrate the <strong>multiple linear regression</strong> model.</p>
<p><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> of Base R is used to calibrate a multiple linear regression model. The model output is stored in an lm object called <em>condo.mlr</em>. - <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> is used to print the model output.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.mlr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_HAWKER_MARKET</span>   <span class="op">+</span></span>
<span>    <span class="va">PROX_KINDERGARTEN</span>   <span class="op">+</span> <span class="va">PROX_MRT</span>  <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_TOP_PRIMARY_SCH</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_SHOPPING_MALL</span>  <span class="op">+</span> <span class="va">PROX_SUPERMARKET</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> </span>
<span>    <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + 
    PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + 
    PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3475964  -293923   -23069   241043 12260381 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           481728.40  121441.01   3.967 7.65e-05 ***
AREA_SQM               12708.32     369.59  34.385  &lt; 2e-16 ***
AGE                   -24440.82    2763.16  -8.845  &lt; 2e-16 ***
PROX_CBD              -78669.78    6768.97 -11.622  &lt; 2e-16 ***
PROX_CHILDCARE       -351617.91  109467.25  -3.212  0.00135 ** 
PROX_ELDERLYCARE      171029.42   42110.51   4.061 5.14e-05 ***
PROX_URA_GROWTH_AREA   38474.53   12523.57   3.072  0.00217 ** 
PROX_HAWKER_MARKET     23746.10   29299.76   0.810  0.41782    
PROX_KINDERGARTEN     147468.99   82668.87   1.784  0.07466 .  
PROX_MRT             -314599.68   57947.44  -5.429 6.66e-08 ***
PROX_PARK             563280.50   66551.68   8.464  &lt; 2e-16 ***
PROX_PRIMARY_SCH      180186.08   65237.95   2.762  0.00582 ** 
PROX_TOP_PRIMARY_SCH    2280.04   20410.43   0.112  0.91107    
PROX_SHOPPING_MALL   -206604.06   42840.60  -4.823 1.57e-06 ***
PROX_SUPERMARKET      -44991.80   77082.64  -0.584  0.55953    
PROX_BUS_STOP         683121.35  138353.28   4.938 8.85e-07 ***
NO_Of_UNITS             -231.18      89.03  -2.597  0.00951 ** 
FAMILY_FRIENDLY       140340.77   47020.55   2.985  0.00289 ** 
FREEHOLD              359913.01   49220.22   7.312 4.38e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 755800 on 1417 degrees of freedom
Multiple R-squared:  0.6518,    Adjusted R-squared:  0.6474 
F-statistic: 147.4 on 18 and 1417 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section><section id="revising-the-model" class="level3" data-number="4.4"><h3 data-number="4.4" class="anchored" data-anchor-id="revising-the-model">
<span class="header-section-number">4.4</span> Revising the model</h3>
<p>With reference to the report above, it is clear that not all the independent variables are statistically significant. We will revised the model by <strong>removing those variables which are not statistically significant, including <em>PROX_HAWKER_MARKET</em>, <em>PROX_KINDERGARTEN</em>, <em>PROX_TOP_PRIMARY_SCH</em>, and <em>PROX_SUPERMARKET</em>.</strong></p>
<p>Now, we are ready to calibrate the revised model.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.mlr1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_ELDERLYCARE</span>  <span class="op">+</span> <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PARK</span> <span class="op">+</span> <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_SHOPPING_MALL</span><span class="op">+</span> <span class="va">PROX_BUS_STOP</span> <span class="op">+</span> </span>
<span>    <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>,</span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_MRT + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_PARK + 
    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + 
    FAMILY_FRIENDLY + FREEHOLD, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 756000 on 1421 degrees of freedom
Multiple R-squared:  0.6507,    Adjusted R-squared:  0.6472 
F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The output above shows that all explanatory variables are now statistically significant at 95% confident level.</p>
</section><section id="preparing-publication-quality-table-gtsummary-method" class="level3" data-number="4.5"><h3 data-number="4.5" class="anchored" data-anchor-id="preparing-publication-quality-table-gtsummary-method">
<span class="header-section-number">4.5</span> Preparing Publication Quality Table: gtsummary method</h3>
<p>The <a href="https://www.danieldsjoberg.com/gtsummary/index.html"><strong>gtsummary</strong></a> package provides an elegant and flexible way to create publication-ready summary tables in R. In the code chunk below, <a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_regression.html"><code>tbl_regression()</code></a> is used to create a well formatted regression report.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tbl_regression</span><span class="op">(</span><span class="va">condo.mlr1</span>, intercept <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="cwreirbycl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cwreirbycl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cwreirbycl thead, #cwreirbycl tbody, #cwreirbycl tfoot, #cwreirbycl tr, #cwreirbycl td, #cwreirbycl th {
  border-style: none;
}

#cwreirbycl p {
  margin: 0;
  padding: 0;
}

#cwreirbycl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cwreirbycl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cwreirbycl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cwreirbycl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cwreirbycl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cwreirbycl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwreirbycl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cwreirbycl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cwreirbycl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cwreirbycl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cwreirbycl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cwreirbycl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cwreirbycl .gt_spanner_row {
  border-bottom-style: hidden;
}

#cwreirbycl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cwreirbycl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cwreirbycl .gt_from_md > :first-child {
  margin-top: 0;
}

#cwreirbycl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cwreirbycl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cwreirbycl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cwreirbycl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cwreirbycl .gt_row_group_first td {
  border-top-width: 2px;
}

#cwreirbycl .gt_row_group_first th {
  border-top-width: 2px;
}

#cwreirbycl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwreirbycl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cwreirbycl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cwreirbycl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwreirbycl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwreirbycl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cwreirbycl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cwreirbycl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cwreirbycl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cwreirbycl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cwreirbycl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwreirbycl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cwreirbycl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cwreirbycl .gt_left {
  text-align: left;
}

#cwreirbycl .gt_center {
  text-align: center;
}

#cwreirbycl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cwreirbycl .gt_font_normal {
  font-weight: normal;
}

#cwreirbycl .gt_font_bold {
  font-weight: bold;
}

#cwreirbycl .gt_font_italic {
  font-style: italic;
}

#cwreirbycl .gt_super {
  font-size: 65%;
}

#cwreirbycl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cwreirbycl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cwreirbycl .gt_indent_1 {
  text-indent: 5px;
}

#cwreirbycl .gt_indent_2 {
  text-indent: 10px;
}

#cwreirbycl .gt_indent_3 {
  text-indent: 15px;
}

#cwreirbycl .gt_indent_4 {
  text-indent: 20px;
}

#cwreirbycl .gt_indent_5 {
  text-indent: 25px;
}

#cwreirbycl .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#cwreirbycl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">(Intercept)</td>
<td class="gt_row gt_center" headers="estimate">527,633</td>
<td class="gt_row gt_center" headers="conf.low">315,417, 739,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">AREA_SQM</td>
<td class="gt_row gt_center" headers="estimate">12,778</td>
<td class="gt_row gt_center" headers="conf.low">12,057, 13,498</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">AGE</td>
<td class="gt_row gt_center" headers="estimate">-24,688</td>
<td class="gt_row gt_center" headers="conf.low">-30,092, -19,284</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_CBD</td>
<td class="gt_row gt_center" headers="estimate">-77,131</td>
<td class="gt_row gt_center" headers="conf.low">-88,436, -65,826</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_CHILDCARE</td>
<td class="gt_row gt_center" headers="estimate">-318,473</td>
<td class="gt_row gt_center" headers="conf.low">-530,250, -106,696</td>
<td class="gt_row gt_center" headers="p.value">0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_MRT</td>
<td class="gt_row gt_center" headers="estimate">-294,745</td>
<td class="gt_row gt_center" headers="conf.low">-406,394, -183,096</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_ELDERLYCARE</td>
<td class="gt_row gt_center" headers="estimate">185,576</td>
<td class="gt_row gt_center" headers="conf.low">107,303, 263,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_URA_GROWTH_AREA</td>
<td class="gt_row gt_center" headers="estimate">39,163</td>
<td class="gt_row gt_center" headers="conf.low">16,105, 62,222</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_PARK</td>
<td class="gt_row gt_center" headers="estimate">570,505</td>
<td class="gt_row gt_center" headers="conf.low">442,004, 699,006</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_PRIMARY_SCH</td>
<td class="gt_row gt_center" headers="estimate">159,856</td>
<td class="gt_row gt_center" headers="conf.low">41,698, 278,014</td>
<td class="gt_row gt_center" headers="p.value">0.008</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_SHOPPING_MALL</td>
<td class="gt_row gt_center" headers="estimate">-220,947</td>
<td class="gt_row gt_center" headers="conf.low">-292,668, -149,226</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_BUS_STOP</td>
<td class="gt_row gt_center" headers="estimate">682,482</td>
<td class="gt_row gt_center" headers="conf.low">418,616, 946,348</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">NO_Of_UNITS</td>
<td class="gt_row gt_center" headers="estimate">-245</td>
<td class="gt_row gt_center" headers="conf.low">-418, -73</td>
<td class="gt_row gt_center" headers="p.value">0.005</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">FAMILY_FRIENDLY</td>
<td class="gt_row gt_center" headers="estimate">146,308</td>
<td class="gt_row gt_center" headers="conf.low">54,321, 238,295</td>
<td class="gt_row gt_center" headers="p.value">0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">FREEHOLD</td>
<td class="gt_row gt_center" headers="estimate">350,600</td>
<td class="gt_row gt_center" headers="conf.low">255,448, 445,752</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody>
<tfoot><tr class="gt_sourcenotes odd">
<td colspan="4" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr></tfoot>
</table>
</div>
</div>
</div>
<p>With gtsummary package, model statistics can be included in the report by either appending them to the report table using <code>add_glance_table()</code> or adding as a table source note using <code>add_glance_source_note()</code> as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tbl_regression</span><span class="op">(</span><span class="va">condo.mlr1</span>, </span>
<span>               intercept <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_glance_source_note</span><span class="op">(</span></span>
<span>    label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">sigma</span> <span class="op">~</span> <span class="st">"\U03C3"</span><span class="op">)</span>,</span>
<span>    include <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r.squared</span>, <span class="va">adj.r.squared</span>, </span>
<span>                <span class="va">AIC</span>, <span class="va">statistic</span>,</span>
<span>                <span class="va">p.value</span>, <span class="va">sigma</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="ekzrcwegaa" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ekzrcwegaa table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ekzrcwegaa thead, #ekzrcwegaa tbody, #ekzrcwegaa tfoot, #ekzrcwegaa tr, #ekzrcwegaa td, #ekzrcwegaa th {
  border-style: none;
}

#ekzrcwegaa p {
  margin: 0;
  padding: 0;
}

#ekzrcwegaa .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ekzrcwegaa .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ekzrcwegaa .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ekzrcwegaa .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ekzrcwegaa .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ekzrcwegaa .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ekzrcwegaa .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ekzrcwegaa .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ekzrcwegaa .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ekzrcwegaa .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ekzrcwegaa .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ekzrcwegaa .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ekzrcwegaa .gt_spanner_row {
  border-bottom-style: hidden;
}

#ekzrcwegaa .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ekzrcwegaa .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ekzrcwegaa .gt_from_md > :first-child {
  margin-top: 0;
}

#ekzrcwegaa .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ekzrcwegaa .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ekzrcwegaa .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ekzrcwegaa .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ekzrcwegaa .gt_row_group_first td {
  border-top-width: 2px;
}

#ekzrcwegaa .gt_row_group_first th {
  border-top-width: 2px;
}

#ekzrcwegaa .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ekzrcwegaa .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ekzrcwegaa .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ekzrcwegaa .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ekzrcwegaa .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ekzrcwegaa .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ekzrcwegaa .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ekzrcwegaa .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ekzrcwegaa .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ekzrcwegaa .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ekzrcwegaa .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ekzrcwegaa .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ekzrcwegaa .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ekzrcwegaa .gt_left {
  text-align: left;
}

#ekzrcwegaa .gt_center {
  text-align: center;
}

#ekzrcwegaa .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ekzrcwegaa .gt_font_normal {
  font-weight: normal;
}

#ekzrcwegaa .gt_font_bold {
  font-weight: bold;
}

#ekzrcwegaa .gt_font_italic {
  font-style: italic;
}

#ekzrcwegaa .gt_super {
  font-size: 65%;
}

#ekzrcwegaa .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ekzrcwegaa .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ekzrcwegaa .gt_indent_1 {
  text-indent: 5px;
}

#ekzrcwegaa .gt_indent_2 {
  text-indent: 10px;
}

#ekzrcwegaa .gt_indent_3 {
  text-indent: 15px;
}

#ekzrcwegaa .gt_indent_4 {
  text-indent: 20px;
}

#ekzrcwegaa .gt_indent_5 {
  text-indent: 25px;
}

#ekzrcwegaa .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ekzrcwegaa div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">(Intercept)</td>
<td class="gt_row gt_center" headers="estimate">527,633</td>
<td class="gt_row gt_center" headers="conf.low">315,417, 739,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">AREA_SQM</td>
<td class="gt_row gt_center" headers="estimate">12,778</td>
<td class="gt_row gt_center" headers="conf.low">12,057, 13,498</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">AGE</td>
<td class="gt_row gt_center" headers="estimate">-24,688</td>
<td class="gt_row gt_center" headers="conf.low">-30,092, -19,284</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_CBD</td>
<td class="gt_row gt_center" headers="estimate">-77,131</td>
<td class="gt_row gt_center" headers="conf.low">-88,436, -65,826</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_CHILDCARE</td>
<td class="gt_row gt_center" headers="estimate">-318,473</td>
<td class="gt_row gt_center" headers="conf.low">-530,250, -106,696</td>
<td class="gt_row gt_center" headers="p.value">0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_MRT</td>
<td class="gt_row gt_center" headers="estimate">-294,745</td>
<td class="gt_row gt_center" headers="conf.low">-406,394, -183,096</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_ELDERLYCARE</td>
<td class="gt_row gt_center" headers="estimate">185,576</td>
<td class="gt_row gt_center" headers="conf.low">107,303, 263,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_URA_GROWTH_AREA</td>
<td class="gt_row gt_center" headers="estimate">39,163</td>
<td class="gt_row gt_center" headers="conf.low">16,105, 62,222</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_PARK</td>
<td class="gt_row gt_center" headers="estimate">570,505</td>
<td class="gt_row gt_center" headers="conf.low">442,004, 699,006</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_PRIMARY_SCH</td>
<td class="gt_row gt_center" headers="estimate">159,856</td>
<td class="gt_row gt_center" headers="conf.low">41,698, 278,014</td>
<td class="gt_row gt_center" headers="p.value">0.008</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_SHOPPING_MALL</td>
<td class="gt_row gt_center" headers="estimate">-220,947</td>
<td class="gt_row gt_center" headers="conf.low">-292,668, -149,226</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_BUS_STOP</td>
<td class="gt_row gt_center" headers="estimate">682,482</td>
<td class="gt_row gt_center" headers="conf.low">418,616, 946,348</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">NO_Of_UNITS</td>
<td class="gt_row gt_center" headers="estimate">-245</td>
<td class="gt_row gt_center" headers="conf.low">-418, -73</td>
<td class="gt_row gt_center" headers="p.value">0.005</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">FAMILY_FRIENDLY</td>
<td class="gt_row gt_center" headers="estimate">146,308</td>
<td class="gt_row gt_center" headers="conf.low">54,321, 238,295</td>
<td class="gt_row gt_center" headers="p.value">0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">FREEHOLD</td>
<td class="gt_row gt_center" headers="estimate">350,600</td>
<td class="gt_row gt_center" headers="conf.low">255,448, 445,752</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody>
<tfoot>
<tr class="gt_sourcenotes odd">
<td colspan="4" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr>
<tr class="gt_sourcenotes even">
<td colspan="4" class="gt_sourcenote">R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</td>
</tr>
</tfoot>
</table>
</div>
</div>
</div>
</section><section id="regression-diagnostics" class="level3" data-number="4.6"><h3 data-number="4.6" class="anchored" data-anchor-id="regression-diagnostics">
<span class="header-section-number">4.6</span> Regression Diagnostics</h3>
<p>Regression diagnostics are a set of procedures used to check if a regression model’s assumptions are met and how well the model fits the data. These diagnostics involve checking for issues like non-linear relationships, non-normal errors, non-constant variance, and influential observations to ensure the model’s conclusions are valid and reliable. Common methods include graphical analysis, like residual plots and QQ-plots, and quantitative tests</p>
<p>In this section, we would like to introduce you a fantastic R package specially programmed for performing OLS regression diagnostics. It is called <code>olsrr</code>. It provides a collection of very useful methods for building better multiple linear regression models:</p>
<ul>
<li>comprehensive regression output</li>
<li>residual diagnostics</li>
<li>measures of influence</li>
<li>heteroskedasticity tests</li>
<li>collinearity diagnostics</li>
<li>model fit assessment</li>
<li>variable contribution assessment</li>
<li>variable selection procedures</li>
</ul>
<section id="multicollinearity-test" class="level4" data-number="4.6.1"><h4 data-number="4.6.1" class="anchored" data-anchor-id="multicollinearity-test">
<span class="header-section-number">4.6.1</span> Multicollinearity test</h4>
<p>Multicollinearity occurs when independent variables are not truly independent, meaning a change in one is associated with a change in another. This makes it hard for the model to isolate each variable’s influence on the outcome.</p>
<p>Performing a multicollinearity test is crucial in multiple linear regression because it ensures the reliability and interpretability of the model’s results. High multicollinearity, where independent variables are highly correlated, inflates the variance of the estimated coefficients, making them unstable, unreliable, and difficult to interpret. This instability can lead to misleading statistical conclusions, such as a variable appearing statistically insignificant when it is not.</p>
<p>In the code chunk below, the <code>check_collinearity()</code> of <code>performance</code> package is used to test if there are sign of multicollinearity.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_collinearity</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

                 Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
             AREA_SQM 1.15 [1.09, 1.23]     1.07      0.87     [0.81, 0.92]
                  AGE 1.41 [1.33, 1.52]     1.19      0.71     [0.66, 0.75]
             PROX_CBD 1.57 [1.47, 1.69]     1.25      0.64     [0.59, 0.68]
       PROX_CHILDCARE 3.26 [3.00, 3.56]     1.81      0.31     [0.28, 0.33]
             PROX_MRT 1.91 [1.78, 2.07]     1.38      0.52     [0.48, 0.56]
     PROX_ELDERLYCARE 1.52 [1.42, 1.63]     1.23      0.66     [0.61, 0.70]
 PROX_URA_GROWTH_AREA 1.33 [1.26, 1.43]     1.15      0.75     [0.70, 0.80]
            PROX_PARK 1.21 [1.15, 1.29]     1.10      0.83     [0.77, 0.87]
     PROX_PRIMARY_SCH 2.21 [2.05, 2.40]     1.49      0.45     [0.42, 0.49]
   PROX_SHOPPING_MALL 1.48 [1.39, 1.60]     1.22      0.67     [0.63, 0.72]
        PROX_BUS_STOP 2.85 [2.62, 3.10]     1.69      0.35     [0.32, 0.38]
          NO_Of_UNITS 1.45 [1.36, 1.56]     1.20      0.69     [0.64, 0.73]
      FAMILY_FRIENDLY 1.38 [1.30, 1.48]     1.17      0.72     [0.67, 0.77]
             FREEHOLD 1.44 [1.36, 1.55]     1.20      0.69     [0.65, 0.74]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr.vif</span> <span class="op">&lt;-</span> <span class="fu">check_collinearity</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mlr.vif</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since the VIF of the independent variables are less than 10. We can safely conclude that there are no sign of multicollinearity among the independent variables.</p>
</section><section id="test-for-non-linearity" class="level4" data-number="4.6.2"><h4 data-number="4.6.2" class="anchored" data-anchor-id="test-for-non-linearity">
<span class="header-section-number">4.6.2</span> Test for Non-Linearity</h4>
<p>In multiple linear regression, it is important for us to test the assumption that linearity and additivity of the relationship between dependent and independent variables.</p>
<p><code>ols_plot_resid_fit()</code> of <strong>olsrr</strong> package is used to perform linearity assumption test.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_model</span><span class="op">(</span><span class="va">condo.mlr1</span>,</span>
<span>            check <span class="op">=</span> <span class="st">"linearity"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure above reveals that most of the data poitns are scattered around the 0 line, hence we can safely conclude that the relationships between the dependent variable and independent variables are linear.</p>
</section><section id="test-for-normality-assumption" class="level4" data-number="4.6.3"><h4 data-number="4.6.3" class="anchored" data-anchor-id="test-for-normality-assumption">
<span class="header-section-number">4.6.3</span> Test for Normality Assumption</h4>
<p>The normality assumption test for multiple linear regression checks if the <strong>model’s residuals (the differences between observed and predicted values) are normally distributed</strong>. This is crucial for accurate hypothesis testing and confidence intervals. To test this, you can use visual methods like histograms and Q-Q plots of the residuals, or conduct statistical tests like Shapiro-Wilk test and Kolmogorov-Smirnov test.</p>
<p><code>check_normality()</code> of <strong>performance</strong> package is used to perform normality assumption test on condo.mlr1 model.</p>
<p><code>check_normality()</code> calls stats::shapiro.test and checks the standardized residuals (or studentized residuals for mixed models) for normal distribution. Note that this formal test almost always yields significant results for the distribution of residuals and visual inspection (e.g.&nbsp;Q-Q plots) are preferable.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_normality</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
</div>
<p>The print above reveals that the p-value of the normality assumption test is less than alpha value of 0.05. Hence we reject the normality assumption at 95% confident level.</p>
<p><code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> of <strong>see</strong> package can be used to plot a the output of <code>check_normality()</code> for visual inspection as shown below.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">check_normality</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span>, </span>
<span>     type <span class="op">=</span> <span class="st">"qq"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Q-Q plot above below shows that majority of the data points are felt along the zero line.</p>
<p>Another way to check for normality assumption visual is by using <code>check_model()</code> of performance package.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_model</span><span class="op">(</span><span class="va">condo.mlr1</span>,</span>
<span>            check<span class="op">=</span> <span class="st">"normality"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure reveals that the residual of the multiple linear regression model (i.e.&nbsp;condo.mlr1) resembles normal distribution.</p>
</section><section id="testing-for-spatial-autocorrelation" class="level4" data-number="4.6.4"><h4 data-number="4.6.4" class="anchored" data-anchor-id="testing-for-spatial-autocorrelation">
<span class="header-section-number">4.6.4</span> Testing for Spatial Autocorrelation</h4>
<p>Our hedonic pricing model uses spatial data, violating the standard regression assumption of independent observations. This creates spatial autocorrelation, where nearby properties influence each other, leading to:</p>
<ul>
<li>Unreliable p-values and significance tests</li>
<li>Potentially biased coefficient estimates</li>
<li>Model misspecification (missing key spatial variables)</li>
</ul>
<p>To diagnose this, we perform <strong>Moran’s I test</strong> on the model’s residuals. A significant result indicates the model fails to capture spatial patterns, requiring specialised spatial regression techniques. The first step is exporting the OLS residuals for this test.</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr.output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will join the newly created data frame with <em>condo_resale.sf</em> object.</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">condo_resale.sf</span>, </span>
<span>                        <span class="va">condo.mlr1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span><span class="fu">rename</span><span class="op">(</span>`MLR_RES` <span class="op">=</span> <span class="va">`condo.mlr1.residuals`</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will use the <strong>tmap</strong> package to display the distribution of the residuals on an interactive map.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span>fill_alpha <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">condo_resale.sf</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span></span>
<span>    fill <span class="op">=</span> <span class="st">"MLR_RES"</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">0.7</span>,</span>
<span>    col <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>    fill.scale <span class="op">=</span> <span class="fu">tm_scale</span><span class="op">(</span></span>
<span>      n <span class="op">=</span> <span class="fl">10</span>,</span>
<span>      values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rev.html">rev</a></span><span class="op">(</span></span>
<span>        <span class="fu">brewer.pal</span><span class="op">(</span><span class="fl">11</span>, <span class="st">"RdBu"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>      style <span class="op">=</span> <span class="st">"quantile"</span>,</span>
<span>      midpoint <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span>,</span>
<span>    fill.legend <span class="op">=</span> <span class="fu">tm_legend</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Residuals"</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">tm_title</span><span class="op">(</span><span class="st">"LM Residuals (Quantile Classification)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_layout</span><span class="op">(</span>legend.outside <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_view</span><span class="op">(</span>set_zoom_limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">14</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The figure above shows signs of spatial autocorrelation.</p>
<p>To prove that our observation is indeed true, <strong>Global Moran’s I test</strong> will be performed</p>
<p>First, we will compute the distance-based weight matrix by using <code>st_dist_band()</code> function of <strong>sfdep</strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="va">condo_resale.sf</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    nb <span class="op">=</span> <span class="fu">st_dist_band</span><span class="op">(</span></span>
<span>      <span class="fu">st_geometry</span><span class="op">(</span><span class="va">geometry</span><span class="op">)</span>, </span>
<span>                 upper <span class="op">=</span> <span class="fl">1500</span><span class="op">)</span>,</span>
<span>    wt <span class="op">=</span> <span class="fu">st_weights</span><span class="op">(</span></span>
<span>      <span class="va">nb</span>, style <span class="op">=</span> <span class="st">"W"</span><span class="op">)</span>,</span>
<span>    .before <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, <code>global_moran_perm()</code> of <strong>sfdep</strong> package will be used to perform Moran’s I test for residual spatial autocorrelation</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="fu">global_moran_perm</span><span class="op">(</span></span>
<span>  <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">MLR_RES</span>, </span>
<span>  nb <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">nb</span>, </span>
<span>  wt <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">wt</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span>, </span>
<span>  nsim <span class="op">=</span> <span class="fl">499</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 500 

statistic = 0.14389, observed rank = 500, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>The Global Moran’s I test for residual spatial autocorrelation shows that it’s p-value is less than 0.00000000000000022 which is less than the alpha value of 0.05. Hence, we will reject the null hypothesis that the residuals are randomly distributed.</p>
<p>Since the Observed Global Moran I = 0.14389 which is greater than 0, we can infer than the residuals resemble cluster distribution.</p>
</section></section></section><section id="building-hedonic-pricing-models-using-gwmodel" class="level2" data-number="5"><h2 data-number="5" class="anchored" data-anchor-id="building-hedonic-pricing-models-using-gwmodel">
<span class="header-section-number">5</span> Building Hedonic Pricing Models using GWmodel</h2>
<p>The next section models hedonic pricing using both the fixed and adaptive bandwidth schemes.</p>
<section id="building-fixed-bandwidth-gwr-model" class="level3" data-number="5.1"><h3 data-number="5.1" class="anchored" data-anchor-id="building-fixed-bandwidth-gwr-model">
<span class="header-section-number">5.1</span> Building Fixed Bandwidth GWR Model</h3>
<section id="computing-fixed-bandwidth" class="level4" data-number="5.1.1"><h4 data-number="5.1.1" class="anchored" data-anchor-id="computing-fixed-bandwidth">
<span class="header-section-number">5.1.1</span> Computing fixed bandwidth</h4>
<p><code>bw.gwr()</code> of <strong>GWModel</strong> package is used to determine the optimal fixed bandwidth to use in the model. Notice that the argument adaptive is set to FALSE so that we can compute the fixed bandwidth.</p>
<p>There are two possible approaches can be used to determine the stopping rule, they are: CV cross-validation approach and AIC corrected (AICc) approach. We define the stopping rule using <strong>approach</strong> agreement.</p>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bw.fixed</span> <span class="op">&lt;-</span> <span class="fu">bw.gwr</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> </span>
<span>    <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  approach<span class="op">=</span><span class="st">"CV"</span>, </span>
<span>  kernel<span class="op">=</span><span class="st">"gaussian"</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">FALSE</span>, </span>
<span>  longlat<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed bandwidth: 17660.96 CV score: 8.259118e+14 
Fixed bandwidth: 10917.26 CV score: 7.970454e+14 
Fixed bandwidth: 6749.419 CV score: 7.273273e+14 
Fixed bandwidth: 4173.553 CV score: 6.300006e+14 
Fixed bandwidth: 2581.58 CV score: 5.404958e+14 
Fixed bandwidth: 1597.687 CV score: 4.857515e+14 
Fixed bandwidth: 989.6077 CV score: 4.722431e+14 
Fixed bandwidth: 613.7939 CV score: 1.377823e+16 
Fixed bandwidth: 1221.873 CV score: 4.778717e+14 
Fixed bandwidth: 846.0596 CV score: 4.791629e+14 
Fixed bandwidth: 1078.325 CV score: 4.751406e+14 
Fixed bandwidth: 934.7772 CV score: 4.72518e+14 
Fixed bandwidth: 1023.495 CV score: 4.730305e+14 
Fixed bandwidth: 968.6643 CV score: 4.721317e+14 
Fixed bandwidth: 955.7206 CV score: 4.722072e+14 
Fixed bandwidth: 976.6639 CV score: 4.721387e+14 
Fixed bandwidth: 963.7202 CV score: 4.721484e+14 
Fixed bandwidth: 971.7199 CV score: 4.721293e+14 
Fixed bandwidth: 973.6083 CV score: 4.721309e+14 
Fixed bandwidth: 970.5527 CV score: 4.721295e+14 
Fixed bandwidth: 972.4412 CV score: 4.721296e+14 
Fixed bandwidth: 971.2741 CV score: 4.721292e+14 
Fixed bandwidth: 970.9985 CV score: 4.721293e+14 
Fixed bandwidth: 971.4443 CV score: 4.721292e+14 
Fixed bandwidth: 971.5496 CV score: 4.721293e+14 
Fixed bandwidth: 971.3793 CV score: 4.721292e+14 
Fixed bandwidth: 971.3391 CV score: 4.721292e+14 
Fixed bandwidth: 971.3143 CV score: 4.721292e+14 
Fixed bandwidth: 971.3545 CV score: 4.721292e+14 
Fixed bandwidth: 971.3296 CV score: 4.721292e+14 
Fixed bandwidth: 971.345 CV score: 4.721292e+14 
Fixed bandwidth: 971.3355 CV score: 4.721292e+14 
Fixed bandwidth: 971.3413 CV score: 4.721292e+14 
Fixed bandwidth: 971.3377 CV score: 4.721292e+14 
Fixed bandwidth: 971.34 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 
Fixed bandwidth: 971.3408 CV score: 4.721292e+14 
Fixed bandwidth: 971.3403 CV score: 4.721292e+14 
Fixed bandwidth: 971.3406 CV score: 4.721292e+14 
Fixed bandwidth: 971.3404 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 </code></pre>
</div>
</div>
<p>The result shows that the recommended bandwidth is 971.3405 metres.</p>
</section><section id="gwmodel-method---fixed-bandwidth" class="level4" data-number="5.1.2"><h4 data-number="5.1.2" class="anchored" data-anchor-id="gwmodel-method---fixed-bandwidth">
<span class="header-section-number">5.1.2</span> GWModel method - fixed bandwidth</h4>
<p>We can calibrate the gwr model using fixed bandwidth and gaussian kernel.</p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.fixed</span> <span class="op">&lt;-</span> <span class="fu">gwr.basic</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> </span>
<span>    <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  bw<span class="op">=</span><span class="va">bw.fixed</span>, </span>
<span>  kernel <span class="op">=</span> <span class="st">'gaussian'</span>, </span>
<span>  longlat <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output is saved in a list of class “gwrm”. The code below can be used to display the model output.</p>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.fixed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 09:02:18.791244 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.fixed, kernel = "gaussian", 
    longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Fixed bandwidth: 971.3405 
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept            -3.5988e+07 -5.1998e+05  7.6780e+05  1.7412e+06
   AREA_SQM              1.0003e+03  5.2758e+03  7.4740e+03  1.2301e+04
   AGE                  -1.3475e+05 -2.0813e+04 -8.6260e+03 -3.7784e+03
   PROX_CBD             -7.7047e+07 -2.3608e+05 -8.3600e+04  3.4646e+04
   PROX_CHILDCARE       -6.0097e+06 -3.3667e+05 -9.7425e+04  2.9007e+05
   PROX_ELDERLYCARE     -3.5000e+06 -1.5970e+05  3.1971e+04  1.9577e+05
   PROX_URA_GROWTH_AREA -3.0170e+06 -8.2013e+04  7.0749e+04  2.2612e+05
   PROX_MRT             -3.5282e+06 -6.5836e+05 -1.8833e+05  3.6922e+04
   PROX_PARK            -1.2062e+06 -2.1732e+05  3.5383e+04  4.1335e+05
   PROX_PRIMARY_SCH     -2.2695e+07 -1.7066e+05  4.8472e+04  5.1555e+05
   PROX_SHOPPING_MALL   -7.2585e+06 -1.6684e+05 -1.0517e+04  1.5923e+05
   PROX_BUS_STOP        -1.4676e+06 -4.5207e+04  3.7601e+05  1.1664e+06
   NO_Of_UNITS          -1.3170e+03 -2.4822e+02 -3.0846e+01  2.5496e+02
   FAMILY_FRIENDLY      -2.2749e+06 -1.1140e+05  7.6214e+03  1.6107e+05
   FREEHOLD             -9.2067e+06  3.8073e+04  1.5169e+05  3.7528e+05
                             Max.
   Intercept            112793546
   AREA_SQM                 21575
   AGE                     434201
   PROX_CBD               2704596
   PROX_CHILDCARE         1654087
   PROX_ELDERLYCARE      38867814
   PROX_URA_GROWTH_AREA  78515730
   PROX_MRT               3124316
   PROX_PARK             18122425
   PROX_PRIMARY_SCH       4637503
   PROX_SHOPPING_MALL     1529952
   PROX_BUS_STOP         11342182
   NO_Of_UNITS              12907
   FAMILY_FRIENDLY        1720744
   FREEHOLD               6073636
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 438.3804 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 997.6196 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42263.61 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41632.36 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 42515.71 
   Residual sum of squares: 2.53407e+14 
   R-square value:  0.8909912 
   Adjusted R-square value:  0.8430417 

   ***********************************************************************
   Program stops at: 2025-10-18 09:02:20.591251 </code></pre>
</div>
</div>
<p>The report shows that the AICc of the gwr is 42263.61 which is significantly smaller than the globel multiple linear regression model of 42967.1.</p>
</section></section><section id="building-adaptive-bandwidth-gwr-model" class="level3" data-number="5.2"><h3 data-number="5.2" class="anchored" data-anchor-id="building-adaptive-bandwidth-gwr-model">
<span class="header-section-number">5.2</span> Building Adaptive Bandwidth GWR Model</h3>
<p>In this section, we will calibrate the gwr-based hedonic pricing model by using adaptive bandwidth approach.</p>
<section id="computing-the-adaptive-bandwidth" class="level4" data-number="5.2.1"><h4 data-number="5.2.1" class="anchored" data-anchor-id="computing-the-adaptive-bandwidth">
<span class="header-section-number">5.2.1</span> Computing the adaptive bandwidth</h4>
<p><code>bw.gwr()</code> is used to determine the recommended data point to use.</p>
<p>The code chunk used look very similar to the one used to compute the fixed bandwidth except the <code>adaptive</code> argument has changed to <strong>TRUE</strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bw.adaptive</span> <span class="op">&lt;-</span> <span class="fu">bw.gwr</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> </span>
<span>    <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  approach<span class="op">=</span><span class="st">"CV"</span>, </span>
<span>  kernel<span class="op">=</span><span class="st">"gaussian"</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">TRUE</span>, </span>
<span>  longlat<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth: 895 CV score: 7.952401e+14 
Adaptive bandwidth: 561 CV score: 7.667364e+14 
Adaptive bandwidth: 354 CV score: 6.953454e+14 
Adaptive bandwidth: 226 CV score: 6.15223e+14 
Adaptive bandwidth: 147 CV score: 5.674373e+14 
Adaptive bandwidth: 98 CV score: 5.426745e+14 
Adaptive bandwidth: 68 CV score: 5.168117e+14 
Adaptive bandwidth: 49 CV score: 4.859631e+14 
Adaptive bandwidth: 37 CV score: 4.646518e+14 
Adaptive bandwidth: 30 CV score: 4.422088e+14 
Adaptive bandwidth: 25 CV score: 4.430816e+14 
Adaptive bandwidth: 32 CV score: 4.505602e+14 
Adaptive bandwidth: 27 CV score: 4.462172e+14 
Adaptive bandwidth: 30 CV score: 4.422088e+14 </code></pre>
</div>
</div>
<p>The result shows that the 30 is the recommended data points to be used.</p>
</section><section id="constructing-the-adaptive-bandwidth-gwr-model" class="level4" data-number="5.2.2"><h4 data-number="5.2.2" class="anchored" data-anchor-id="constructing-the-adaptive-bandwidth-gwr-model">
<span class="header-section-number">5.2.2</span> Constructing the adaptive bandwidth gwr model</h4>
<p>Now, we can go ahead to calibrate the gwr-based hedonic pricing model by using adaptive bandwidth and gaussian kernel.</p>
<div class="cell">
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.adaptive</span> <span class="op">&lt;-</span> <span class="fu">gwr.basic</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span> <span class="op">+</span> <span class="va">PROX_BUS_STOP</span> <span class="op">+</span></span>
<span>    <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>,</span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  bw<span class="op">=</span><span class="va">bw.adaptive</span>, </span>
<span>  kernel <span class="op">=</span> <span class="st">'gaussian'</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">TRUE</span>, </span>
<span>  longlat <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we can display the model output.</p>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.adaptive</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 09:02:30.471729 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.adaptive, kernel = "gaussian", 
    adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 30 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept            -1.3487e+08 -2.4669e+05  7.7928e+05  1.6194e+06
   AREA_SQM              3.3188e+03  5.6285e+03  7.7825e+03  1.2738e+04
   AGE                  -9.6746e+04 -2.9288e+04 -1.4043e+04 -5.6119e+03
   PROX_CBD             -2.5330e+06 -1.6256e+05 -7.7242e+04  2.6624e+03
   PROX_CHILDCARE       -1.2790e+06 -2.0175e+05  8.7158e+03  3.7778e+05
   PROX_ELDERLYCARE     -1.6212e+06 -9.2050e+04  6.1029e+04  2.8184e+05
   PROX_URA_GROWTH_AREA -7.2686e+06 -3.0350e+04  4.5869e+04  2.4613e+05
   PROX_MRT             -4.3781e+07 -6.7282e+05 -2.2115e+05 -7.4593e+04
   PROX_PARK            -2.9020e+06 -1.6782e+05  1.1601e+05  4.6572e+05
   PROX_PRIMARY_SCH     -8.6418e+05 -1.6627e+05 -7.7853e+03  4.3222e+05
   PROX_SHOPPING_MALL   -1.8272e+06 -1.3175e+05 -1.4049e+04  1.3799e+05
   PROX_BUS_STOP        -2.0579e+06 -7.1461e+04  4.1104e+05  1.2071e+06
   NO_Of_UNITS          -2.1993e+03 -2.3685e+02 -3.4699e+01  1.1657e+02
   FAMILY_FRIENDLY      -5.9879e+05 -5.0927e+04  2.6173e+04  2.2481e+05
   FREEHOLD             -1.6340e+05  4.0765e+04  1.9023e+05  3.7960e+05
                            Max.
   Intercept            18758355
   AREA_SQM                23064
   AGE                     13303
   PROX_CBD             11346650
   PROX_CHILDCARE        2892127
   PROX_ELDERLYCARE      2465671
   PROX_URA_GROWTH_AREA  7384059
   PROX_MRT              1186242
   PROX_PARK             2588497
   PROX_PRIMARY_SCH      3381462
   PROX_SHOPPING_MALL   38038564
   PROX_BUS_STOP        12081592
   NO_Of_UNITS              1010
   FAMILY_FRIENDLY       2072414
   FREEHOLD              1813995
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 350.3088 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1085.691 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 41982.22 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41546.74 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 41914.08 
   Residual sum of squares: 2.528227e+14 
   R-square value:  0.8912425 
   Adjusted R-square value:  0.8561185 

   ***********************************************************************
   Program stops at: 2025-10-18 09:02:32.169496 </code></pre>
</div>
</div>
<p>The report shows that the AICc the adaptive distance gwr is 41982.22 which is even smaller than the AICc of the fixed distance gwr of 42263.61.</p>
</section></section><section id="visualising-gwr-output" class="level3" data-number="5.3"><h3 data-number="5.3" class="anchored" data-anchor-id="visualising-gwr-output">
<span class="header-section-number">5.3</span> Visualising GWR Output</h3>
<p>The output includes key diagnostics beyond regression residuals:</p>
<ul>
<li>Condition Number: Identifies local collinearity; values &gt;30 suggest unstable results.</li>
<li>Local R²: Measures local model fit (0.0-1.0); low values indicate poor performance and potentially missing variables.</li>
<li>Predicted: The fitted y-values from the GWR model.</li>
<li>Residuals: Difference between observed and predicted values (standardised for mapping).</li>
<li>Coefficient Standard Error: Measures coefficient reliability; large errors relative to coefficients indicate local collinearity issues.</li>
</ul>
<p>All results are stored in a spatial data frame (SDF) within the output list, containing coefficients, predictions, standard errors, and t-values.</p>
<section id="converting-sdf-into-sf-data.frame" class="level4" data-number="5.3.1"><h4 data-number="5.3.1" class="anchored" data-anchor-id="converting-sdf-into-sf-data.frame">
<span class="header-section-number">5.3.1</span> Converting SDF into sf data.frame</h4>
<p>To visualise the fields in <strong>SDF</strong>, we need to first covert it into sf data.frame</p>
<div class="cell">
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf.adaptive</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">st_as_sf</span><span class="op">(</span><span class="va">gwr.adaptive</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">st_transform</span><span class="op">(</span>crs<span class="op">=</span><span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glimpse</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 52
$ Intercept               &lt;dbl&gt; 2050011.67, 1633128.24, 3433608.17, 234358.91,…
$ AREA_SQM                &lt;dbl&gt; 9561.892, 16576.853, 13091.861, 20730.601, 672…
$ AGE                     &lt;dbl&gt; -9514.634, -58185.479, -26707.386, -93308.988,…
$ PROX_CBD                &lt;dbl&gt; -120681.94, -149434.22, -259397.77, 2426853.66…
$ PROX_CHILDCARE          &lt;dbl&gt; 319266.925, 441102.177, -120116.816, 480825.28…
$ PROX_ELDERLYCARE        &lt;dbl&gt; -393417.795, 325188.741, 535855.806, 314783.72…
$ PROX_URA_GROWTH_AREA    &lt;dbl&gt; -159980.203, -142290.389, -253621.206, -267929…
$ PROX_MRT                &lt;dbl&gt; -299742.96, -2510522.23, -936853.28, -2039479.…
$ PROX_PARK               &lt;dbl&gt; -172104.47, 523379.72, 209099.85, -759153.26, …
$ PROX_PRIMARY_SCH        &lt;dbl&gt; 242668.03, 1106830.66, 571462.33, 3127477.21, …
$ PROX_SHOPPING_MALL      &lt;dbl&gt; 300881.390, -87693.378, -126732.712, -29593.34…
$ PROX_BUS_STOP           &lt;dbl&gt; 1210615.44, 1843587.22, 1411924.90, 7225577.51…
$ NO_Of_UNITS             &lt;dbl&gt; 104.8290640, -288.3441183, -9.5532945, -161.35…
$ FAMILY_FRIENDLY         &lt;dbl&gt; -9075.370, 310074.664, 5949.746, 1556178.531, …
$ FREEHOLD                &lt;dbl&gt; 303955.61, 396221.27, 168821.75, 1212515.58, 3…
$ y                       &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1…
$ yhat                    &lt;dbl&gt; 2886531.8, 3466801.5, 3616527.2, 5435481.6, 13…
$ residual                &lt;dbl&gt; 113468.16, 413198.52, -291527.20, -1185481.63,…
$ CV_Score                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Stud_residual           &lt;dbl&gt; 0.38207013, 1.01433140, -0.83780678, -2.846146…
$ Intercept_SE            &lt;dbl&gt; 516105.5, 488083.5, 963711.4, 444185.5, 211962…
$ AREA_SQM_SE             &lt;dbl&gt; 823.2860, 825.2380, 988.2240, 617.4007, 1376.2…
$ AGE_SE                  &lt;dbl&gt; 5889.782, 6226.916, 6510.236, 6010.511, 8180.3…
$ PROX_CBD_SE             &lt;dbl&gt; 37411.22, 23615.06, 56103.77, 469337.41, 41064…
$ PROX_CHILDCARE_SE       &lt;dbl&gt; 319111.1, 299705.3, 349128.5, 304965.2, 698720…
$ PROX_ELDERLYCARE_SE     &lt;dbl&gt; 120633.34, 84546.69, 129687.07, 127150.69, 327…
$ PROX_URA_GROWTH_AREA_SE &lt;dbl&gt; 56207.39, 76956.50, 95774.60, 470762.12, 47433…
$ PROX_MRT_SE             &lt;dbl&gt; 185181.3, 281133.9, 275483.7, 279877.1, 363830…
$ PROX_PARK_SE            &lt;dbl&gt; 205499.6, 229358.7, 314124.3, 227249.4, 364580…
$ PROX_PRIMARY_SCH_SE     &lt;dbl&gt; 152400.7, 165150.7, 196662.6, 240878.9, 249087…
$ PROX_SHOPPING_MALL_SE   &lt;dbl&gt; 109268.8, 98906.8, 119913.3, 177104.1, 301032.…
$ PROX_BUS_STOP_SE        &lt;dbl&gt; 600668.6, 410222.1, 464156.7, 562810.8, 740922…
$ NO_Of_UNITS_SE          &lt;dbl&gt; 218.1258, 208.9410, 210.9828, 361.7767, 299.50…
$ FAMILY_FRIENDLY_SE      &lt;dbl&gt; 131474.73, 114989.07, 146607.22, 108726.62, 16…
$ FREEHOLD_SE             &lt;dbl&gt; 115954.0, 130110.0, 141031.5, 138239.1, 210641…
$ Intercept_TV            &lt;dbl&gt; 3.9720784, 3.3460017, 3.5629010, 0.5276150, 1.…
$ AREA_SQM_TV             &lt;dbl&gt; 11.614302, 20.087361, 13.247868, 33.577223, 4.…
$ AGE_TV                  &lt;dbl&gt; -1.6154474, -9.3441881, -4.1023685, -15.524301…
$ PROX_CBD_TV             &lt;dbl&gt; -3.22582173, -6.32792021, -4.62353528, 5.17080…
$ PROX_CHILDCARE_TV       &lt;dbl&gt; 1.000488185, 1.471786337, -0.344047555, 1.5766…
$ PROX_ELDERLYCARE_TV     &lt;dbl&gt; -3.26126929, 3.84626245, 4.13191383, 2.4756745…
$ PROX_URA_GROWTH_AREA_TV &lt;dbl&gt; -2.846248368, -1.848971738, -2.648105057, -5.6…
$ PROX_MRT_TV             &lt;dbl&gt; -1.61864578, -8.92998600, -3.40075727, -7.2870…
$ PROX_PARK_TV            &lt;dbl&gt; -0.83749312, 2.28192684, 0.66565951, -3.340617…
$ PROX_PRIMARY_SCH_TV     &lt;dbl&gt; 1.59230221, 6.70194543, 2.90580089, 12.9836104…
$ PROX_SHOPPING_MALL_TV   &lt;dbl&gt; 2.753588422, -0.886626400, -1.056869486, -0.16…
$ PROX_BUS_STOP_TV        &lt;dbl&gt; 2.0154464, 4.4941192, 3.0419145, 12.8383775, 0…
$ NO_Of_UNITS_TV          &lt;dbl&gt; 0.480589953, -1.380026395, -0.045279967, -0.44…
$ FAMILY_FRIENDLY_TV      &lt;dbl&gt; -0.06902748, 2.69655779, 0.04058290, 14.312764…
$ FREEHOLD_TV             &lt;dbl&gt; 2.6213469, 3.0452799, 1.1970499, 8.7711485, 1.…
$ Local_R2                &lt;dbl&gt; 0.8846744, 0.8899773, 0.8947007, 0.9073605, 0.…
$ geometry                &lt;POINT [m]&gt; POINT (22085.12 29951.54), POINT (25656.…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">gwr.adaptive</span><span class="op">$</span><span class="va">SDF</span><span class="op">$</span><span class="va">yhat</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
  171347  1102001  1385528  1751842  1982307 13887901 </code></pre>
</div>
</div>
</section></section><section id="visualising-local-r2" class="level3" data-number="5.4"><h3 data-number="5.4" class="anchored" data-anchor-id="visualising-local-r2">
<span class="header-section-number">5.4</span> Visualising local R2</h3>
<p>We create an interactive point symbol map.</p>
<div class="cell">
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span>fill_alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span>col <span class="op">=</span> <span class="st">"Local_R2"</span>,</span>
<span>          border.col <span class="op">=</span> <span class="st">"gray60"</span>,</span>
<span>          border.lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_view</span><span class="op">(</span>set.zoom.limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">14</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="visualising-coefficient-estimates" class="level3" data-number="5.5"><h3 data-number="5.5" class="anchored" data-anchor-id="visualising-coefficient-estimates">
<span class="header-section-number">5.5</span> Visualising coefficient estimates</h3>
<p>Creating an interactive point symbol map.</p>
<div class="cell">
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span>
<span><span class="va">AREA_SQM_SE</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span>col <span class="op">=</span> <span class="st">"AREA_SQM_SE"</span>,</span>
<span>          border.col <span class="op">=</span> <span class="st">"gray60"</span>,</span>
<span>          border.lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_view</span><span class="op">(</span>set.zoom.limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">14</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">AREA_SQM_TV</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span>col <span class="op">=</span> <span class="st">"AREA_SQM_TV"</span>,</span>
<span>          border.col <span class="op">=</span> <span class="st">"gray60"</span>,</span>
<span>          border.lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_view</span><span class="op">(</span>set.zoom.limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">14</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tmap_arrange</span><span class="op">(</span><span class="va">AREA_SQM_SE</span>, <span class="va">AREA_SQM_TV</span>, </span>
<span>             asp<span class="op">=</span><span class="fl">1</span>, ncol<span class="op">=</span><span class="fl">2</span>,</span>
<span>             sync <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Hands-on_Ex07_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tmap_mode</span><span class="op">(</span><span class="st">"plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->



</body></html>