---
title: "In-class Exercise 10: Market Area Analysis for Retail and Service Locations using Huff model"
date: "Nov 13, 2025"
date-modified: "last-modified"
author: Linh Nguyen
execute:
  echo: true
  eval: true
  freeze: auto
  message: false
  warning: false
  error: false
format:
  html:
    code-link: true       # Clickable function links
    toc: true             # Table of contents
    code-fold: true       # Foldable code
    code-tools: true      # Code tools menu
number-sections: false
number-offset: 1
editor: visual
---

## Import R Packages

```{r}
pacman::p_load(sf, tidyverse, MCI, tmap, ggstatsplot)
```

## Import Data

```{r}
stores <- st_read(
  dsn = "data/geospatial",
  layer = "STORES_TC")
```

```{r}
town <- st_read(
  dsn = "data/geospatial",
  layer = "TOWN_TC")
```

```{r}
village <- st_read(
  dsn = "data/geospatial",
  layer = "VILLAGE_TC")
```

```{r}
pop2019 <- read_csv(
  "data/aspatial/pop2019.csv")

store_sales <- read_csv(
  "data/aspatial/Store_sales_data.csv")
```

```{r}
summary(store_sales)
```

## Data Preparation

### Aggregating store sales

```{r}
store_sales_aggre <- store_sales %>%
  group_by(`Store Code`) %>%
  summarise(
    "Total_Bill" = sum(Bills, na.rm = TRUE),
    "Total_Sales" = sum(Amount, na.rm = TRUE))
```

### Relational join

```{r}
stores <- stores %>%
  left_join(store_sales_aggre,
            by = join_by(
              Store_CD == `Store Code`)) %>%
  mutate(Store_size = 100)
```

```{r}
summary(stores)
```

### Tidying pop2019 data.frame

```{r}
glimpse(pop2019)
```

```{r}
glimpse(village)
```

```{r}
pop2019 <- pop2019 %>%
  mutate(V_ID = str_remove_all(
    V_ID, "-"))
```

```{r}
village <- village %>%
  left_join(pop2019,
            by = join_by(
              VILLCODE == V_ID))
```

### Check for missing or zero values

```{r}
summary(village)
```

```{r}
village <- village %>%
  filter(!is.na(P_CNT)) 
```

```{r}
any(is.na(village$H_CNT))
```

```{r}
any(is.na(village$P_CNT))
```

```{r}
any(is.na(village$M_CNT))
```

```{r}
any(is.na(village$F_CNT))
```

## Computing Distance Matrix

```{r}
village_center <- st_point_on_surface(village)
distmat <- st_distance(village_center, stores) 
```

```{r}
rownames(distmat) <- village$`VILLCODE`
colnames(distmat) <- stores$`Store_CD`

distmat_long <- distmat %>%
  as.data.frame() %>%
  rownames_to_column(var = "VILLCODE") %>%
  pivot_longer(
    cols = -VILLCODE,
    names_to = "Store_CD",
    values_to = "distance"
  ) %>%
  mutate(distance = as.numeric(distance)) 
```

## Preparing Interaction Matrix

```{r}
interaction_matrix <- distmat_long %>%
  left_join(
    stores %>% 
      st_drop_geometry() %>% 
      select(Store_CD, Store_size),
    by = "Store_CD") %>%
  relocate(
    distance, .after = last_col())
```

```{r}
summary(interaction_matrix)
```

## Computing Huff model

```{r}
huff_share <- huff.shares(
  interaction_matrix, "VILLCODE", "Store_CD", 
  "Store_size", "distance")
```

### Trade area analysis for a single store

```{r}
market_share <- huff_share %>%
  filter(Store_CD == "TG")
```

```{r}
Trade_area <- village %>%
  left_join(market_share)
```

```{r}
selected_store <- stores %>%
  filter(Store_CD == "TG")
```

```{r}
tm_shape(Trade_area) +
  tm_polygons(fill = "p_ij",
              fill.scale = tm_scale_intervals(
                style = "quantile", 
                n = 10,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "Patronage Probability")) +
  tm_shape(selected_store) +
    tm_dots(size = 0.3,
            fill = "red",
            col = "black") +
  tm_title("Distribution of Patronage Probability of Store BT by village") +
  tm_layout(frame = TRUE) +
  tm_borders(fill_alpha = 0.5) +
  tm_compass(type="8star", size = 2) +
  tm_scalebar() +
  tm_grid(alpha =0.2) 
```

### Store sales analysis

```{r}
huff_share_pp <- huff_share %>%
  left_join(village %>% 
      st_drop_geometry() %>% 
      select(VILLCODE, P_CNT),
    by = "VILLCODE") %>%
  relocate(
    distance, .after = last_col())
```

```{r}
huff_total <- shares.total(
  huff_share_pp, "VILLCODE", "Store_CD",
  "p_ij", "P_CNT")
```

```{r}
store_sales_est <- stores %>%
  left_join(huff_total,
            by = join_by(
              "Store_CD" == "suppliers_single"))
```

```{r}
store_sales_nongeom <- store_sales_est %>% st_drop_geometry()

ggscatterstats(
  store_sales_nongeom,
  x = sum_E_j,
  y = Total_Sales)
```

```{r}
huff_share_wider <- huff_share %>%
  select(VILLCODE, Store_CD, p_ij) %>%
    pivot_wider(names_from = Store_CD, 
                values_from = p_ij)
```
