{
  "hash": "e45cb87f8b8b4aba149b187a1c71463a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5a | Global Measures of Spatial Autocorrelation\"\nsubtitle: \"In this hands-on exercise, you will learn how to compute Global Measures of Spatial Autocorrelation (GMSA) by using spdep package\"\ndate: \"Sep 26, 2025\"\ndate-modified: \"last-modified\"\nauthor: Linh Nguyen\nexecute:\n  echo: true\n  eval: true\n  freeze: auto\n  message: false\n  warning: false\nformat:\n  html:\n    code-link: true\n    toc: true\nnumber-sections: true\nnumber-offset: 1\neditor: visual\n---\n\n## Overview\n\nWe will learn to compute **Global Measures of Spatial Autocorrelation (GMSA)** by using **spdep** package. We will do the following in this hands-on exercise. - import geospatial data using appropriate function(s) of **sf** package - import csv file using appropriate function of readr package - perform relational join using appropriate join function of **dplyr** package - compute Global Spatial Autocorrelation (GSA) statistics using appropriate functions of **spdep** package, plot Moran scatterplot - compute and plot spatial correlogram using appropriate function of **spdep** package - provide statistically correct interpretation of GSA statistics.\n\n## Getting started\n\n### The analytical question\n\nGenerally spatial policies would have development objectives from local government and planners to ensure equal distribution of development in the province, taking China for an example. Our task in this study, hence, is to apply appropriate spatial statistical methods to discover if [*development are evenly distributed geographically*]{style=\"color: #B95E82;\"}. If the answer is **No**. Then, our next question will be “[*is there sign of spatial clustering?*]{style=\"color: #B95E82;\"}”. And, if the answer for this question is **yes**, then our next question will be “[*where are these clusters?*]{style=\"color: #B95E82;\"}”\n\nIn this case study, we will use China's data to examine the spatial pattern of a selected development indicator (i.e. GDP per capita) of Hunan Provice.\n\n### Setting the Analytical Toolls\n\nWe will use the following packages: **spdep, sf, tmap and tidyverse** packages of R.\n\n| Package | Description |\n|-----------------------|------------------------------------------------|\n| **sf** | importing and handling geospatial data in R |\n| **tidyverse** | wrangling attribute data in R |\n| **spdep** | computing spatial weights, global and local spatial autocorrelation statistics |\n| **tmap** | preparing cartographic quality chropleth map |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse, spdep, tmap)\n```\n:::\n\n\n## The data\n\n### The Study Area and Data\n\nTwo data sets will be used in this hands-on exercise, they are:\n\n-   Hunan province administrative boundary layer at county level: This is a geospatial data set in ESRI shapefile format.\n-   Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.\n\nWe will bring a geospatial data and its associated attribute table into R environment. The geospatial data is in ESRI shapefile format and the attribute table is in csv fomat.\n\n### Import shapefile into R environment\n\nThe code chunk below uses [`st_read()`](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `D:\\ngoclinhnguyen-2806\\ISSS626-GAA\\Hands-on_Ex\\Hands-on_Ex05\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### Import csv file into R environment\n\nNext, we will import *Hunan_2012.csv* into R by using [`read_csv()`](https://readr.tidyverse.org/reference/read_delim.html) of **readr** package. The output is R data frame class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n### Performing relational join\n\nBelow we will update the attribute table of *hunan*’s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe. This is performed using [`left_join()`](https://dplyr.tidyverse.org/reference/mutate-joins.html) of **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, hunan2012) %>%\n  dplyr::select(1:4, 7, 15)\n```\n:::\n\n\n### Visualising Regional Development Indicator\n\nNow, we are going to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012 using `qtm()` of **tmap** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-5-1.png){width=1152}\n:::\n:::\n\n\n## Global Measures of Spatial Autocorrelation\n\nIn this section, we will compute global spatial autocorrelation statistics and to perform spatial complete randomness test for global spatial autocorrelation.\n\n### Computing Contiguity Spatial Weights\n\nBefore we can compute the global spatial autocorrelation statistics, we need to construct a spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\nIn the code chunk below, [`poly2nb()`](https://r-spatial.github.io/spdep/reference/poly2nb.html) of **spdep** package is used to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries.\n\nMore specifically, the code chunk below is used to compute Queen contiguity weight matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\nThe summary report above shows that there are **88 area units** in Hunan. The most connected area unit has **11 neighbour**s. There are two area units with only one neighbours.\n:::\n:::::\n\n### Row-standardised weights matrix\n\nThis step is about creating a spatial lag, which is a value that summarises the variable (like income) across a central area's immediate neighbors. The method chosen is to assign an equal weight to every neighboring area, known as style=\"W\" (Row-Standardized Weights).\n\nThe weight for each neighbor is calculated simply as the fraction (/1number of neighbors). For example, if a county has four neighbors, each one is assigned a weight of 0.25. The final spatial lag is then computed by multiplying each neighbor's income value by this weight and summing the products. The primary appeal of this approach is that it is the most intuitive and easiest way to summarize the surrounding values.\n\nThe significant limitation of using the equal-weight style=\"W\" is the \"edge effect.\" Areas located along the boundaries of the study region naturally have fewer neighbors than those in the center.\n\nWhen a polygon has fewer neighbors, those few neighbors receive a disproportionately large weight. This causes the calculated spatial lag for the boundary area to be heavily influenced by a limited sample of surrounding data, which may over or under-estimate the true underlying spatial pattern (spatial autocorrelation). Although this drawback exists, we use style=\"W\" for its simplicity in this example. More robust alternative options—such as style=\"B\" (Binary Weights) are available for more serious spatial analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Learning**\n:::\n\n::: markgoals-container\n-   The input of [`nb2listw()`](https://r-spatial.github.io/spdep/reference/nb2listw.html) must be an object of class **nb**. The syntax of the function has two major arguments, namely style and zero.poly.\n\n-   *style* can take values “W”, “B”, “C”, “U”, “minmax” and “S”.\n\n    -   B is the basic binary coding\n\n    -   W is row standardised (sums over all links to n)\n\n    -   C is globally standardised (sums over all links to n)\n\n    -   U is equal to C divided by the number of neighbours (sums over all links to unity)\n\n    -   S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n)\n\n-   If *zero policy* is set to TRUE, weights vectors of zero length are inserted for regions without neighbour in the neighbours list. These will in turn generate lag values of zero, equivalent to the sum of products of the zero row t(rep(0, length=length(neighbours))) %\\*% x, for arbitrary numerical vector x of length length(neighbours). The spatially lagged value of x for the zero-neighbour region will then be zero, which may (or may not) be a sensible choice.\n:::\n:::::\n\n## Global Measures of Spatial Autocorrelation: Moran’s I\n\nWe will perform Moran’s I statistics testing by using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of **spdep**.\n\n:::::::::::: panel-tabset\n## Maron's I test\n\nBelow we will performs Moran’s I statistical testing using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of **spdep**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, listw = rswm_q,\n           zero.policy = TRUE, na.action = na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\nThere is statistically significant positive spatial autocorrelation in GDPPC across Hunan province. - p-value = 1.095e-06 is well below any conventional significance level (0.001, 0.01, 0.05) - Z-score = 4.74 indicates the observed Moran's I is 4.74 standard deviations above what would be expected under spatial randomness. - This provides very strong evidence to **reject the null hypothesis of spatial randomness** - Moran's I score 0.300749970 shows moderate positive spatial clustering. Areas with similar GDPPC tend to cluster together, but it's not an extremely strong pattern.\n:::\n:::::\n\n## Computing Monte Carlo Moran's I\n\nLet's perform permutation test for Moran’s I statistic using [`moran.mc()`](https://r-spatial.github.io/spdep/reference/moran.mc.html) of **spdep**. A total of 1000 simulation will be performed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\nThere is statistically significant positive spatial autocorrelation in GDP per capita across Hunan province. - p-value = 0.001 indicates strong statistical significance - Observed rank = 1000 means observed Moran's I value was the highest among all 1000 values. This means none of the 999 random permutations produced a Moran's I value as high as the observed value. - Moran's I = 0.30075 confirms moderate positive spatial autocorrelation. Areas with similar GDP per capita are significantly clustered together geographically.\n:::\n:::::\n\n## Visualise Monte Carlo Moran's I\n\nTo examine the simulated Moran's test statistics in greater detail, we can plot the distribution of the statistical values as a histogram. Below we will use [`hist()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist) and [`abline()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/abline) of R Graphics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\n**Plot histogram**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#D0DDD0\")\nhist(bperm$res, freq=TRUE, \n     breaks=20, xlab=\"Simulated Moran's I\",\n     col=\"#FFECC0\")\nabline(v=0, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**ggplot2**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(res = bperm$res), aes(x = res)) +\n  geom_histogram(bins = 20, \n                 fill = \"#FFECC0\", \n                 color = \"grey\",\n                 boundary = 0) +\n  geom_vline(xintercept = 0, color = \"red\", size = 1) +\n  labs(x = \"Simulated Moran's I\",\n       y = \"Frequency\",\n       title = \"Histogram of bperm$res\") +\n  theme_minimal() +\n  theme(\n    plot.background = element_rect(fill = \"#D0DDD0\", color = NA),\n    panel.background = element_rect(fill = \"#D0DDD0\", color = NA),\n    panel.grid = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\n-   This histogram displays exhibits an approximately normal distribution with slight positive skewness centered near -0.05. The distribution demonstrates the expected range of Moran's I values under the null hypothesis of spatial randomness, with the majority of simulated statistics falling within the interval \\[-0.15, +0.05\\].\n-   The observed test statistic of 0.301 represents an extreme outlier, positioned far beyond the upper tail of this reference distribution. **This extreme positioning validates the Monte Carlo p-value of 0.001 and confirms statistically significant positive spatial autocorrelation at α = 0.001.**\n-   The evidence strongly rejects the null hypothesis of spatial independence, indicating that the observed spatial clustering of GDPPC substantially exceeds what would be expected under random spatial arrangements.\n:::\n:::::\n::::::::::::\n\n## Global Measures of Spatial Autocorrelation: Geary’s C\n\nWe will perform Geary’s C statistics testing by using appropriate functions of **spdep** package.\n\n:::::::::::: panel-tabset\n\n## Geary’s C test\n\nWe will perform Geary’s C test for spatial autocorrelation by using [`geary.test()`](https://r-spatial.github.io/spdep/reference/geary.test.html) of **spdep**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\n-   The Geary C statistic = 0.691 is substantially below the expected value of 1.000 under spatial randomness, with a highly significant p-value = 0.0001526 (α \\< 0.001). The standardized test statistic = 3.61 indicates the observed value is 3.61 standard deviations below the null expectation, providing strong statistical evidence to reject the null hypothesis of spatial independence.\n-   These results from both global spatial autocorrelation statistics provide robust evidence that GDPPC in Hunan province exhibits significant spatial clustering, and confirms the presence of regional economic spillover effects.\n:::\n:::::\n\n## Computing Monte Carlo Geary’s C\n\nWe will perform permutation test for Geary’s C statistic using [`geary.mc()`](https://r-spatial.github.io/spdep/reference/geary.mc.html) of spdep.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\nThe observed Geary C statistic = 0.69072 achieved an observed rank = 1 out of 1000, indicating it was the lowest value among all simulations. This extreme ranking confirms that none of the 999 random permutations produced a Geary's C value as low as the observed data, so yields a p-value = 0.001 and provides very strong statistical evidence against the null hypothesis of spatial randomness.\n:::\n:::::\n\n## Visualise Monte Carlo Geary’s C\n\nFinally we will plot the simulated values to show the distribution in a histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#D0DDD0\")\nhist(bperm$res, freq=TRUE, \n     breaks=20, xlab=\"Simulated Geary c\",\n     col=\"#FFF1F1\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n::::: markgoals\n::: markgoals-header\n**Findings**\n:::\n\n::: markgoals-container\n-   The distribution appears approximately normal, which is expected for Geary's C under the null hypothesis of spatial randomness. The distribution is centered around 1.0, which corresponds to the theoretical expectation of Geary's C = 1.0 under spatial independence.\n-   The observed Geary C statistic = 0.69072 would fall far to the left of this entire distribution, well beyond the left tail. The histogram validates the p-value = 0.001 by demonstrating that values below 0.7 are virtually non-existent under spatial randomness.\n-   This visualisation confirms the exceptionally strong statistical significance of the spatial autocorrelation detected in Hunan's GDPPC data, as the observed spatial clustering is far more extreme than what random spatial arrangements would produce.\n:::\n:::::\n::::::::::::\n\n## Spatial Correlogram\n\nSpatial correlograms are great to examine patterns of spatial autocorrelation in your data or model residuals. They show **how correlated are pairs of spatial observations when you increase the distance (lag) between them** . They are plots of some index of autocorrelation (Moran’s I or Geary’s c) against distance. Although **correlograms** are not as fundamental as variograms (a keystone concept of geostatistics), they are very useful as an exploratory and descriptive tool. For this purpose they actually provide richer information than variograms.\n\n## Computing Moran’s I correlogram\n\nBelow [`sp.correlogram()`](https://r-spatial.github.io/spdep/reference/sp.correlogram.html) of **spdep** package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The **plot()** of base Graph is then used to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, method=\"I\", style=\"W\")\nplot(MI_corr,\n     col.main = \"#B95E82\")\nabline(h = 0, col = \"red\", lty = 2, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Computing Geary’s C correlogram and plot\n",
    "supporting": [
      "Hands-on_Ex05a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}