{
  "hash": "9919834463b708ad40f4cd1e29e63851",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 6 | \"\nsubtitle: \"This exercise applies advanced geospatial statistical methods to analyze bus passenger mobility patterns across Singapore. By leveraging Local Measures of Spatial Association (LMSA) and Emerging Hot Spot Analysis (EHSA), we move beyond simple mapping to identify where and how passenger demand clusters evolve over time. These insights can inform more responsive urban planning and public transport service optimization.\"\ndate: \"Oct 20, 2025\"\ndate-modified: \"last-modified\"\nauthor: Linh Nguyen\nexecute:\n  echo: true\n  eval: true\n  freeze: auto\n  message: false\n  warning: false\nformat:\n  html:\n    code-link: true        # Clickable function links\n    toc: true             # Table of contents\n    code-fold: true       # Foldable code\n    code-tools: true      # Code tools menu\nnumber-sections: false\nnumber-offset: 1\neditor: visual\n---\n\n## Overview\n\nUrban mobility patterns reveal how cities function and evolve. This exercise analyzes bus passenger boarding patterns across Singapore using advanced geospatial statistical methods. By applying Local Measures of Spatial Association (LMSA) and Emerging Hot Spot Analysis (EHSA), we identify where passenger demand clusters are located and how they evolve over time during different periods of the week.\n\n### Objectives\n\n-   Identify spatial clustering patterns in bus passenger boarding volumes across Singapore's hexagonal traffic analysis zones using Local Moran's I, Local Geary's C, and Getis-Ord Gi\\* statistics.\n\n-   Detect emerging mobility trends by analyzing how passenger demand hotspots evolve over time – whether they are new, intensifying, diminishing, or sporadic.\n\n-   Compare mobility patterns across weekday morning peak, weekday afternoon peak, and weekend/holiday periods.\n\n### Analysis Questions\n\n-   Where are the spatial hotspots and coldspots of bus passenger boarding volumes during weekday morning peak, weekday afternoon peak, and weekend/holiday periods?\n\n-   How do passenger boarding patterns differ spatially across neighborhoods and planning areas in Singapore?\n\n-   Are there significant spatial outliers – locations with unusually high or low passenger volumes compared to their surroundings?\n\n-   How are passenger demand hotspots evolving over time – are they new, intensifying, diminishing, or exhibiting sporadic patterns across the observed period?\n\n-   What are the implications of these spatial and temporal patterns for public transport planning and urban mobility management?\n\n### The Data\n\n| Dataset | Description | Source | Format |\n|------------------|------------------|------------------|------------------|\n| Passenger Volume by Origin Destination Bus Stops | Bus passenger tap-on/tap-off records for spatial-temporal mobility analysis | [LTA DataMall](https://datamall.lta.gov.sg/content/datamall/en.html) | CSV |\n| Bus Stop Location | Geospatial coordinates and identifiers for bus stops across Singapore | [LTA DataMall](https://datamall.lta.gov.sg/content/datamall/en.html) | ESRI Shapefile |\n| Master Plan 2019 Subzone Boundary (No Sea) | Planning area and subzone boundaries for spatial context | [Data.gov.sg](https://data.gov.sg) | ESRI Shapefile |\n\n## Set up R environment\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Install and Load R packages\"}\npacman::p_load(sfdep, tmap, sf, knitr, httr, rvest, tidyverse)\n```\n:::\n\n\n## Data Import & Preparation\n\n### Importing Geospatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Import SG boundaries data\"}\nmpsz <- read_rds(\"data/rds/mpsz_sf.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Import and transform bus stop data\"}\nBusStop <- st_read(dsn = \"data/geospatial/BusStopLocation_Aug2025\",\n                   layer = \"BusStop\") %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\n### Importing Aspatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Import SG Bus Trip\"}\nodbus <- read_csv(\"data/geospatial/origin_destination_bus_202508.csv\")\n```\n:::\n\n\n### Filtering Bus Stops Within Singapore\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Extract bus stops within Singapore boundaries only\"}\nBusStop_in_SG <- st_join(\n  BusStop, mpsz,\n  join = st_within,\n  left = FALSE\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Visualize bus stops on Singapore map\"}\ntm_shape(mpsz) + \n  tm_polygons() + \n  tm_shape(BusStop_in_SG) + \n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Deriving Analytical Hexagon\n\n### Creating Hexagonal Grid\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Generate hexagonal grid with 375m cell size\"}\nhexagon <- st_make_grid(mpsz,\n                        cellsize = 375,\n                        what = \"polygons\",\n                        square = FALSE) %>%\n  st_sf()\n```\n:::\n\n\n### Filtering hexagons with bus stops\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Retain only hexagons containing bus stops\"}\nhexagon$n_collisions = \n  length(st_intersects(\n    hexagon, BusStop_in_SG\n  ))\n\nhexagon <- filter(hexagon, n_collisions > 0)\n```\n:::\n\n\n### Assigning ids to each hexagon\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Create unique identifiers for each hexagon\"}\nhexagon <- hexagon %>%\n  select(, -n_collisions)\n\nhexagon$HEX_ID <- sprintf(\n  \"H%04d\", seq_len(nrow(hexagon))) %>%\n  as.factor()\n\nkable(head(hexagon))\n```\n:::\n\n\n## Preparing Trip Generation Data\n\n### Cleaning Trip Data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Select and rename relevant columns\"}\ntrips <- odbus %>%\n  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%\n  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%\n  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%\n  rename(TRIPS = TOTAL_TRIPS)\ntrips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)\n\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|\n|:----------|:----------------|-----------:|-----:|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|\n|10099      |WEEKENDS/HOLIDAY |          13|    31|\n|64601      |WEEKENDS/HOLIDAY |          21|     3|\n|53009      |WEEKENDS/HOLIDAY |          16|    10|\n|80051      |WEEKENDS/HOLIDAY |          18|     4|\n|70031      |WEEKDAY          |          14|     1|\n\n\n:::\n:::\n\n\n### Linking Bus Stops to Hexagons\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Map bus stops to their corresponding hexagons\"}\nbs_hex <- st_intersection(\n  BusStop, hexagon) %>%\n  st_drop_geometry() %>%\n  select(c(BUS_STOP_N, HEX_ID))\nkable(head(bs_hex))\n```\n\n::: {.cell-output-display}\n\n\n|     |BUS_STOP_N |HEX_ID |\n|:----|:----------|:------|\n|3092 |25059      |H0398  |\n|2439 |25751      |H0615  |\n|241  |26379      |H0618  |\n|2258 |26369      |H0619  |\n|2554 |25761      |H0668  |\n|3611 |26389      |H0671  |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Join trip data with hexagon assignments\"}\ntrips <- inner_join(trips, bs_hex)\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|HEX_ID |\n|:----------|:----------------|-----------:|-----:|:------|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|H10990 |\n|10099      |WEEKENDS/HOLIDAY |          13|    31|H6826  |\n|64601      |WEEKENDS/HOLIDAY |          21|     3|H9056  |\n|53009      |WEEKENDS/HOLIDAY |          16|    10|H7917  |\n|80051      |WEEKENDS/HOLIDAY |          18|     4|H8613  |\n|70031      |WEEKDAY          |          14|     1|H8832  |\n\n\n:::\n:::\n\n\n### Aggregating Trips by Time Period\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Define time period classifications\"}\n# Weekday Morning Peak: 6am-9am (hours 6, 7, 8)\n# Weekday Afternoon Peak: 5pm-8pm (hours 17, 18, 19)\n# Weekend/Holiday: 11am-8pm (hours 11-19)\n\ntrips <- trips %>%\n  mutate(TIME_PERIOD = case_when(\n    DAY_TYPE == \"WEEKDAY\" & HOUR_OF_DAY >= 6 & HOUR_OF_DAY <= 8 ~ \"Weekday_Morning_Peak\",\n    DAY_TYPE == \"WEEKDAY\" & HOUR_OF_DAY >= 17 & HOUR_OF_DAY <= 19 ~ \"Weekday_Afternoon_Peak\",\n    DAY_TYPE %in% c(\"WEEKENDS/HOLIDAY\") & HOUR_OF_DAY >= 11 & HOUR_OF_DAY <= 19 ~ \"Weekend_Holiday\",\n    TRUE ~ \"Other\"\n  ))\n\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |DAY_TYPE         | HOUR_OF_DAY| TRIPS|HEX_ID |TIME_PERIOD     |\n|:----------|:----------------|-----------:|-----:|:------|:---------------|\n|84671      |WEEKENDS/HOLIDAY |           9|     3|H10990 |Other           |\n|10099      |WEEKENDS/HOLIDAY |          13|    31|H6826  |Weekend_Holiday |\n|64601      |WEEKENDS/HOLIDAY |          21|     3|H9056  |Other           |\n|53009      |WEEKENDS/HOLIDAY |          16|    10|H7917  |Weekend_Holiday |\n|80051      |WEEKENDS/HOLIDAY |          18|     4|H8613  |Weekend_Holiday |\n|70031      |WEEKDAY          |          14|     1|H8832  |Other           |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Aggregate trips by hexagon and time period\"}\ntrips_hex <- trips %>%\n  filter(TIME_PERIOD != \"Other\") %>%\n  group_by(HEX_ID, TIME_PERIOD) %>%\n  summarise(TOTAL_TRIPS = sum(TRIPS, na.rm = TRUE),\n            .groups = \"drop\")\n\nkable(head(trips_hex, 10))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID |TIME_PERIOD            | TOTAL_TRIPS|\n|:------|:----------------------|-----------:|\n|H0398  |Weekday_Afternoon_Peak |         849|\n|H0398  |Weekday_Morning_Peak   |         308|\n|H0398  |Weekend_Holiday        |        1237|\n|H0615  |Weekday_Afternoon_Peak |          45|\n|H0615  |Weekday_Morning_Peak   |          26|\n|H0615  |Weekend_Holiday        |          50|\n|H0618  |Weekday_Afternoon_Peak |         223|\n|H0618  |Weekday_Morning_Peak   |          74|\n|H0618  |Weekend_Holiday        |         159|\n|H0619  |Weekday_Afternoon_Peak |         221|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Pivot data to wide format for analysis\"}\ntrips_hex_wide <- trips_hex %>%\n  pivot_wider(names_from = TIME_PERIOD,\n              values_from = TOTAL_TRIPS,\n              values_fill = 0)\n\nkable(head(trips_hex_wide))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | Weekday_Afternoon_Peak| Weekday_Morning_Peak| Weekend_Holiday|\n|:------|----------------------:|--------------------:|---------------:|\n|H0398  |                    849|                  308|            1237|\n|H0615  |                     45|                   26|              50|\n|H0618  |                    223|                   74|             159|\n|H0619  |                    221|                   78|             194|\n|H0668  |                    736|                  193|             407|\n|H0671  |                    398|                   67|             276|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Join aggregated trips with hexagon geometry\"}\nhexagon_trips <- hexagon %>%\n  left_join(trips_hex_wide, by = \"HEX_ID\") %>%\n  replace_na(list(Weekday_Morning_Peak = 0,\n                  Weekday_Afternoon_Peak = 0,\n                  Weekend_Holiday = 0))\n\nkable(head(hexagon_trips))\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID | Weekday_Afternoon_Peak| Weekday_Morning_Peak| Weekend_Holiday|geometry                       |\n|:------|----------------------:|--------------------:|---------------:|:------------------------------|\n|H0001  |                      0|                    0|               0|POLYGON ((2480.038 15856.97... |\n|H0002  |                      0|                    0|               0|POLYGON ((2480.038 16506.49... |\n|H0003  |                      0|                    0|               0|POLYGON ((2480.038 17156.01... |\n|H0004  |                      0|                    0|               0|POLYGON ((2480.038 17805.53... |\n|H0005  |                      0|                    0|               0|POLYGON ((2480.038 18455.05... |\n|H0006  |                      0|                    0|               0|POLYGON ((2480.038 19104.57... |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Summary statistics of trips by time period\"}\nsummary_stats <- trips_hex %>%\n  group_by(TIME_PERIOD) %>%\n  summarise(\n    Min = min(TOTAL_TRIPS),\n    Q1 = quantile(TOTAL_TRIPS, 0.25),\n    Median = median(TOTAL_TRIPS),\n    Mean = mean(TOTAL_TRIPS),\n    Q3 = quantile(TOTAL_TRIPS, 0.75),\n    Max = max(TOTAL_TRIPS),\n    SD = sd(TOTAL_TRIPS),\n    Total_Hexagons = n()\n  )\n\nkable(summary_stats)\n```\n\n::: {.cell-output-display}\n\n\n|TIME_PERIOD            | Min|      Q1| Median|     Mean|      Q3|    Max|       SD| Total_Hexagons|\n|:----------------------|---:|-------:|------:|--------:|-------:|------:|--------:|--------------:|\n|Weekday_Afternoon_Peak |   1| 1549.50|   4434| 9769.810| 10080.5| 467963| 22545.26|           2139|\n|Weekday_Morning_Peak   |   1|  657.50|   4271| 9709.962| 12505.0| 288060| 16542.43|           2135|\n|Weekend_Holiday        |   2|  961.75|   3932| 8952.446| 10144.5| 334516| 18845.34|           2152|\n\n\n:::\n:::\n\n\n## Exploratory Data Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Filter hexagons with trips for analysis\"}\nhexagon_trips_filtered <- hexagon_trips %>%\n  filter(Weekday_Morning_Peak > 0 | \n         Weekday_Afternoon_Peak > 0 | \n         Weekend_Holiday > 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Calculate common breaks for all three time periods\"}\n# Calculate common quantile breaks across all three periods\nall_trips <- c(hexagon_trips_filtered$Weekday_Morning_Peak,\n               hexagon_trips_filtered$Weekday_Afternoon_Peak,\n               hexagon_trips_filtered$Weekend_Holiday)\n\ncommon_breaks <- quantile(all_trips, \n                          probs = seq(0, 1, length.out = 7), \n                          na.rm = TRUE)\n\nprint(\"Common breaks for all three periods:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Common breaks for all three periods:\"\n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Calculate common breaks for all three time periods\"}\nprint(common_breaks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       0% 16.66667% 33.33333%       50% 66.66667% 83.33333%      100% \n        0       465      1809      4167      7933     15153    467963 \n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n\n### Weekday Morning Peak (6am-9am)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Statistical summary of weekday morning peak trips\"}\nsummary(hexagon_trips_filtered$Weekday_Morning_Peak)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n     0.0    601.5   4159.0   9619.8  12367.0 288060.0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of Weekday Morning Peak time trips\"}\nggplot(data = hexagon_trips_filtered, \n       aes(x = Weekday_Morning_Peak)) +\n  geom_histogram(bins = 10, \n                 fill = \"steelblue\", \n                 color = \"black\") +\n  scale_x_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - Weekday Morning Peak (Linear Scale)\",\n       x = \"Total Trips\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of weekday morning peak trips (Log scale)\"}\nggplot(data = hexagon_trips_filtered %>% filter(Weekday_Morning_Peak > 0), \n       aes(x = Weekday_Morning_Peak)) +\n  geom_histogram(bins = 30, \n                 fill = \"steelblue\", \n                 color = \"black\") +\n  scale_x_log10(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - Weekday Morning Peak (Log Scale)\",\n       x = \"Total Trips (log scale)\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nThe distribution is heavily right-skewed, with most hexagons (approximately 1,800) generating fewer than 50,000 trips during morning peak hours. This reveals significant spatial inequality in demand: while the majority of active hexagons serve moderate passenger volumes, a small number of critical nodes experience exceptionally high boarding activity exceeding 100,000 trips. This concentration suggests opportunities for targeted capacity planning in high-demand corridors.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Spatial distribution of weekday morning peak trips (common scale)\"}\ntm_shape(mpsz) +\n  tm_polygons(col = \"lightgrey\", border.col = \"white\") +\ntm_shape(hexagon_trips_filtered) +\n  tm_fill(col = \"Weekday_Morning_Peak\",\n          palette = \"YlOrRd\",\n          breaks = common_breaks,\n          title = \"Total Trips\") +\n  tm_borders(alpha = 0.3) +\n  tm_layout(main.title = \"Passenger Trips by Origin - Weekday Morning Peak (6am-9am)\",\n            main.title.size = 1,\n            legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe spatial distribution of weekday morning peak passenger trips reveals distinct clustering patterns across Singapore. High-intensity boarding activity (dark red hexagons) is concentrated in several key areas: the Central Business District (CBD) and surrounding central regions, major residential estates in the north and northeastern areas, and established HDB townships in the western part of Singapore. These patterns reflect typical morning commute behavior, where passengers board buses from residential neighborhoods heading toward employment centers.\n\nNotable spatial heterogeneity is evident, with mid-to-high trip generation hexagons (orange to red) forming contiguous clusters, suggesting neighborhood-level demand patterns rather than isolated hotspots. The eastern and northeastern regions show moderate activity levels, while certain peripheral areas display lower boarding volumes.\n\nThe quantile classification reveals that the top 20% of hexagons (darkest red) handle significantly higher passenger volumes (18,337 to 288,060 trips), indicating substantial spatial inequality in bus service demand. This concentration suggests that targeted service planning focusing on these high-demand corridors could efficiently serve a large proportion of morning peak passengers. The spatial continuity of medium-to-high demand areas also indicates potential for effective trunk-and-feeder route optimization.\n\n### Weekday Afternoon Peak (5pm-8pm)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Statistical summary of weekday afternoon peak trips\"}\nsummary(hexagon_trips_filtered$Weekday_Afternoon_Peak)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0    1498    4314    9697   10044  467963 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of Weekday afternoon Peak time trips (Linear Scale)\"}\nggplot(data = hexagon_trips_filtered, \n       aes(x = Weekday_Afternoon_Peak)) +\n  geom_histogram(bins = 10, \n                 fill = \"steelblue\", \n                 color = \"black\") +\n  scale_x_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - Weekday Afternoon Peak (Linear Scale)\",\n       x = \"Total Trips\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of weekday afternoon peak trips (Log Scale)\"}\nggplot(data = hexagon_trips_filtered %>% filter(Weekday_Afternoon_Peak > 0), \n       aes(x = Weekday_Afternoon_Peak)) +\n  geom_histogram(bins = 30, \n                 fill = \"coral\", \n                 color = \"black\") +\n  scale_x_log10(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - Weekday Afternoon Peak (Log Scale)\",\n       x = \"Total Trips (log scale)\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThe afternoon peak distribution differs significantly from morning peak. Morning shows a broader, flatter distribution with trip volumes spreading relatively evenly from 1,000 to 10,000+ trips. In contrast, afternoon exhibits a more concentrated, bell-shaped pattern with a sharp peak around 2,000-3,000 trips and a steeper drop-off. The afternoon distribution has fewer hexagons with extremely high trip volumes (10,000+), while morning has a longer right tail indicating more hexagons with very high boarding activity. This suggests more uniformity in afternoon trip generation across hexagons compared to morning's greater variation in activity levels.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Spatial distribution of weekday afternoon peak trips (common scale)\"}\ntm_shape(mpsz) +\n  tm_polygons(col = \"lightgrey\", border.col = \"white\") +\ntm_shape(hexagon_trips_filtered) +\n  tm_fill(col = \"Weekday_Afternoon_Peak\",\n          palette = \"YlOrRd\",\n          breaks = common_breaks,\n          title = \"Total Trips\") +\n  tm_borders(alpha = 0.3) +\n  tm_layout(main.title = \"Passenger Trips by Origin - Weekday Afternoon Peak (5pm-8pm)\",\n            main.title.size = 1,\n            legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe afternoon peak spatial distribution displays high-intensity boarding activity across multiple areas of Singapore, with dark red hexagons visible in the central region and various other locations across the island. The pattern shows widespread moderate-to-high activity (orange to red) across much of the developed area.\n\nWhile the histogram revealed some differences in trip volume distribution between morning and afternoon peaks, the spatial maps show broadly similar geographic patterns. Both periods exhibit high-activity hexagons distributed across various regions rather than concentrated in a single area. The afternoon peak maintains substantial boarding activity across multiple zones, similar to the morning pattern, though the specific intensity levels at individual hexagons may vary between the two periods.\n\n### Weekend/Holiday (11am-8pm)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Statistical summary of weekend/holiday trips\"}\nsummary(hexagon_trips_filtered$Weekend_Holiday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0     952    3927    8940   10132  334516 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of weekend/holiday Peak time trips (Linear Scale)\"}\nggplot(data = hexagon_trips_filtered, \n       aes(x = Weekend_Holiday)) +\n  geom_histogram(bins = 10, \n                 fill = \"steelblue\", \n                 color = \"black\") +\n  scale_x_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - weekend/holiday Peak (Linear Scale)\",\n       x = \"Total Trips\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\nThe linear scale histogram shows extreme right-skew similar to weekday patterns, with approximately 1,900+ hexagons concentrated in the low trip range (0-50,000 trips). Only a small number of hexagons exceed 50,000 trips, with the maximum reaching around 100,000-150,000 trips, lower than weekday morning peak's maximum of nearly 300,000 trips.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Distribution of weekend/holiday trips (Log Scale)\"}\nggplot(data = hexagon_trips_filtered %>% filter(Weekend_Holiday > 0), \n       aes(x = Weekend_Holiday)) +\n  geom_histogram(bins = 30, \n                 fill = \"mediumseagreen\", \n                 color = \"black\") +\n  scale_x_log10(labels = scales::comma) +\n  labs(title = \"Distribution of Passenger Trips - Weekend/Holiday (Log Scale)\",\n       x = \"Total Trips (log scale)\",\n       y = \"Number of Hexagons\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nOn log scale, the weekend/holiday distribution displays a bell-shaped pattern with peak around 2,000-4,000 trips. The distribution appears more symmetric and concentrated compared to weekday morning's flatter spread, but similar to weekday afternoon's bell-shaped form. The right tail extends to approximately 100,000 trips, indicating fewer extreme high-volume hexagons than weekday peaks.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Spatial distribution of weekend/holiday trips (common scale)\"}\ntm_shape(mpsz) +\n  tm_polygons(col = \"lightgrey\", border.col = \"white\") +\ntm_shape(hexagon_trips_filtered) +\n  tm_fill(col = \"Weekend_Holiday\",\n          palette = \"YlOrRd\",\n          breaks = common_breaks,\n          title = \"Total Trips\") +\n  tm_borders(alpha = 0.3) +\n  tm_layout(main.title = \"Passenger Trips by Origin - Weekend/Holiday (11am-8pm)\",\n            main.title.size = 1,\n            legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe weekend/holiday spatial pattern shows high-intensity boarding activity (dark red hexagons) distributed across multiple regions of Singapore, similar to weekday patterns. Red and orange hexagons are visible in central, northern, western, and eastern areas. The overall spatial distribution appears comparable to both weekday morning and afternoon peaks, with moderate-to-high activity spread across developed areas rather than showing a distinctly different geographic pattern.\n\n:::\n\n### Comparative Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Compare trip volumes across time periods\"}\ntrips_comparison <- hexagon_trips_filtered %>%\n  st_drop_geometry() %>%\n  summarise(\n    Weekday_Morning_Total = sum(Weekday_Morning_Peak, na.rm = TRUE),\n    Weekday_Morning_Mean = mean(Weekday_Morning_Peak, na.rm = TRUE),\n    Weekday_Morning_Median = median(Weekday_Morning_Peak, na.rm = TRUE),\n    Weekday_Afternoon_Total = sum(Weekday_Afternoon_Peak, na.rm = TRUE),\n    Weekday_Afternoon_Mean = mean(Weekday_Afternoon_Peak, na.rm = TRUE),\n    Weekday_Afternoon_Median = median(Weekday_Afternoon_Peak, na.rm = TRUE),\n    Weekend_Holiday_Total = sum(Weekend_Holiday, na.rm = TRUE),\n    Weekend_Holiday_Mean = mean(Weekend_Holiday, na.rm = TRUE),\n    Weekend_Holiday_Median = median(Weekend_Holiday, na.rm = TRUE)\n  ) %>%\n  pivot_longer(everything(), \n               names_to = c(\"Period\", \".value\"),\n               names_pattern = \"(.+)_(Total|Mean|Median)\") %>%\n  mutate(Period = str_replace_all(Period, \"_\", \" \"))\n\nkable(trips_comparison, \n      digits = 0,\n      caption = \"Comparison of Trip Volumes Across Time Periods\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Trip Volumes Across Time Periods\n\n|Period            |    Total| Mean| Median|\n|:-----------------|--------:|----:|------:|\n|Weekday Morning   | 20730768| 9620|   4159|\n|Weekday Afternoon | 20897624| 9697|   4314|\n|Weekend Holiday   | 19265664| 8940|   3927|\n\n\n:::\n:::\n\n\nThe summary statistics reveal similar overall trip volumes across the three time periods. Weekday morning peak records the highest total trips (20,730,768) and mean per hexagon (9,620), followed closely by weekday afternoon peak (20,897,621 total; 9,697 mean). Weekend/holiday shows slightly lower volumes (19,265,664 total; 8,940 mean). \n\nThe median values are notably consistent across all periods (4,159 for morning, 4,314 for afternoon, 3,927 for weekend), suggesting comparable central tendencies despite differences in distribution shapes observed in the histograms.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Prepare data for box plot comparison\"}\ntrips_boxplot <- hexagon_trips_filtered %>%\n  st_drop_geometry() %>%\n  select(Weekday_Morning_Peak, Weekday_Afternoon_Peak, Weekend_Holiday) %>%\n  pivot_longer(everything(), \n               names_to = \"TIME_PERIOD\", \n               values_to = \"TOTAL_TRIPS\") %>%\n  filter(TOTAL_TRIPS > 0) %>%\n  mutate(TIME_PERIOD = factor(TIME_PERIOD,\n                               levels = c(\"Weekday_Morning_Peak\", \n                                        \"Weekday_Afternoon_Peak\", \n                                        \"Weekend_Holiday\"),\n                               labels = c(\"Weekday\\nMorning Peak\", \n                                        \"Weekday\\nAfternoon Peak\", \n                                        \"Weekend/\\nHoliday\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Box plot comparison across time periods\"}\nggplot(data = trips_boxplot, \n       aes(x = TIME_PERIOD, y = TOTAL_TRIPS, fill = TIME_PERIOD)) +\n  geom_boxplot() +\n  scale_y_log10(labels = scales::comma) +\n  scale_fill_manual(values = c(\"steelblue\", \"coral\", \"mediumseagreen\")) +\n  labs(title = \"Comparison of Trip Distribution Across Time Periods\",\n       x = \"Time Period\",\n       y = \"Total Trips (log scale)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        axis.text.x = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\nThe box plots reveal similar distributions across all three time periods on log scale. All three periods show comparable median values (horizontal lines within boxes around 2,000-4,000 trips) and interquartile ranges (box heights). Each period displays numerous outliers above the upper whisker, with weekday afternoon peak showing the most prominent extreme outliers exceeding 100,000 trips. The weekend/holiday distribution has a slightly lower median and narrower interquartile range compared to weekday peaks. \n\nOverall, the three distributions are remarkably similar in shape and spread, with the main differences appearing in the frequency and magnitude of extreme high-value outliers rather than in the typical hexagon's trip volume.\n\n\n\n## Local Measures of Spatial Association (LMSA)\n\n### Computing Spatial Weights\n\n### Local Moran's I Analysis\n\n### Local Geary's C Analysis\n\n### Getis-Ord Gi\\* Analysis\n\n### Comparative Analysis of LMSA Results\n\n## Emerging Hot Spot Analysis (EHSA)\n\n### Creating Space-Time Cube\n\n### Mann-Kendall Trend Test\n\n### EHSA Classification and Visualization\n\n### Temporal Pattern Interpretation\n\n## Conclusions and Recommendations\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}